//! Per-project `game.zig` shim generation, extracted from `root.zig`
//! (behavior-preserving split). Owns the static shim preludes and
//! `generateGameShim`, which emits the tiny re-export module that lets
//! generated flow files resolve `@import("game")`. See
//! labelle-assembler#116 / #275.
//!
//! Bit-identical contract: every byte this module writes lands verbatim in
//! the generated `game.zig`; `generateGameShim`'s `PluginEvents` /
//! `PluginFlowNodes` blocks must stay byte-identical to the ones
//! `main_zig` emits into `main.zig`.

const std = @import("std");
const config = @import("../config.zig");
const main_zig = @import("../main_zig.zig");

/// Static prelude of the per-project `game.zig` shim. Re-exports the
/// engine's default `Game` type and its associated `EntityId` so
/// generated flow files (emitted by `flow-codegen`) can satisfy
/// `@import("game")` with `Game` and `EntityId` decls at the module
/// root. Closes the remaining gap on labelle-gui#96 / labelle-assembler#116.
///
/// Limitation: this re-exports `engine.Game = GameWith(void)`, which
/// won't match the project's own `AssembledGame = engine.GameConfig(...)`
/// instantiation. Flow files compile in isolation (the `@import("game")`
/// resolves and `Game` / `EntityId` are valid decls), but a full
/// `zig build` will still fail when codegen emits bare identifiers like
/// `Position` that aren't in the flow file's lexical scope — that's a
/// separate codegen-side gap tracked on labelle-gui (see PR body).
///
/// `generateGameShim` (below) appends a `PluginEvents` re-export when
/// the project declares plugins; flow-codegen's new-form `OnEvent`
/// handler reflects against `@FieldType(game.PluginEvents, "<tag>")` to
/// derive the payload signature.
const game_shim_prelude =
    \\//! Generated by labelle-assembler — DO NOT EDIT.
    \\//! Re-exports engine types as `Game` and `EntityId` so generated
    \\//! flow files (`scripts/flows/*.zig`) resolve `@import("game")`.
    \\//! See labelle-assembler#116.
    \\
    \\const std = @import("std");
    \\const engine = @import("labelle-engine");
    \\
    \\/// Default engine game type. Codegen emits `game: *Game` parameters
    \\/// at hook entry points; the value passed at runtime is the
    \\/// project's `AssembledGame` instantiation (declared in main.zig).
    \\/// These two types are not identical — see the file header on
    \\/// labelle-assembler#116 for the documented limitation.
    \\pub const Game = engine.Game;
    \\
    \\/// Entity identifier type. Mirrors `Game.EntityType` so flow files
    \\/// can declare `entity: EntityId` parameters without reaching into
    \\/// the engine module directly.
    \\pub const EntityId = engine.Game.EntityType;
    \\
    \\
;

/// Static prelude of the `.labelle/tests/` `game.zig` shim
/// (labelle-assembler#275). Unlike the default prelude above — which
/// re-exports `engine.Game` (the mock-ECS / stub-render convenience
/// instantiation) — the tests target instantiates `Game` over the
/// project's REAL ECS backend (`@import("ecs_backend")`) so a
/// backend-agnostic `labelle test` can drive a plugin's systems
/// headless.
///
/// Why this is required, not just nicer: a plugin's ECS iteration
/// (e.g. `box2d`'s `iter.deinit(game.ecs_backend.alloc)`) is compiled
/// against the project's configured ECS backend, whose `QueryIterator`
/// `deinit` takes an allocator. The mock backend's `deinit` takes none,
/// so `box2d.Systems.tick(&g, dt)` fails to compile against `engine.Game`
/// even though the plugin's `labelle-core` is already unified onto
/// `core_mod` in the generated `build.zig`. Pointing the test game's
/// `ecs_backend` at the same `@import("ecs_backend")` module the plugin
/// resolves makes the iterator types — and the underlying core — match.
/// Closes labelle-assembler#275 (and the practical half of #116 for the
/// test target).
///
/// Everything else stays a stub: `StubRender` (no GPU; provides the
/// no-op `markPositionDirty` plugins call from `postTick`), `StubInput`
/// / `StubAudio` / `StubGui`, no hooks (`void`), and `void` `GameEvents`
/// (so a plugin's tolerant `emitGameEvent` folds to a no-op exactly as it
/// does for `engine.Game`). The empty `Components` registry is fine: the
/// engine's generic `addComponent`/`getComponent`/`query` are type-driven
/// and don't consult it.
const game_shim_tests_prelude_header =
    \\//! Generated by labelle-assembler — DO NOT EDIT.
    \\//! `.labelle/tests/` game shim (labelle-assembler#275). Instantiates
    \\//! `Game` over the project's REAL ECS backend so `labelle test` can
    \\//! drive plugin systems headless. See #275 / #116.
    \\
    \\const std = @import("std");
    \\const engine = @import("labelle-engine");
    \\
;

/// Body of the tests-target shim shared by every ECS choice: stub
/// renderer/input/audio/gui, no hooks, empty components, no game events.
/// `EcsBackend` (and its `Entity`) are declared by the caller-selected
/// header that precedes this block.
const game_shim_tests_prelude_body =
    \\
    \\const EmptyComponents = struct {
    \\    pub fn has(comptime _: []const u8) bool {
    \\        return false;
    \\    }
    \\    pub fn names() []const []const u8 {
    \\        return &.{};
    \\    }
    \\};
    \\
    \\/// The project's configured game, instantiated for headless tests:
    \\/// REAL ecs backend (matches the plugin's core) + stubs for render,
    \\/// input, audio, gui. See the file header / labelle-assembler#275.
    \\pub const Game = engine.GameConfig(
    \\    engine.core.StubRender(EcsBackend.Entity),
    \\    EcsBackend,
    \\    engine.StubInput,
    \\    engine.StubAudio,
    \\    engine.StubGui,
    \\    void,
    \\    engine.core.StubLogSink,
    \\    EmptyComponents,
    \\    &.{},
    \\    void,
    \\);
    \\
    \\/// Entity identifier type. Mirrors `Game.EntityType` so flow files
    \\/// can declare `entity: EntityId` parameters.
    \\pub const EntityId = Game.EntityType;
    \\
    \\
;

/// Generate the per-project `game.zig` shim. Caller owns the returned
/// bytes. Built from `game_shim_prelude` plus a `PluginEvents` block
/// (RFC-PLUGIN-EVENTS phase 3) when at least one plugin actually
/// declares events, so flow-codegen's new-form `OnEvent` handler can
/// resolve event names against `@FieldType(game.PluginEvents, "<tag>")`
/// through the same `@import("game")` flow files already use. The block
/// is identical to the one `main_zig.writePluginEventsBlock` emits into
/// `main.zig` — same assembler-time AST walk, same qualified variant
/// tags. The `overrideImport(game_mod, "<plugin>", ...)` calls in
/// `build_files.generateBuildZig` wire each plugin module into
/// `game_mod` so the `@import("<plugin>")` calls inside the block
/// resolve.
///
/// Caller passes the pre-computed `plugin_events` list (see
/// `main_zig.discoverPluginEvents`) so the discovery happens once per
/// `generate` invocation rather than twice (shim + main.zig). When the
/// list is empty (declared plugins but no `Events` decls) the shim
/// omits the block entirely — there's nothing for flow-codegen to
/// reflect against.
///
/// `plugin_flow_nodes` (labelle-assembler#240 Gap 1) is the same
/// discovered FlowNode list `main_zig.writePluginFlowNodesBlock` consumes
/// for `main.zig`. Generated flow files emit
/// `@import("game").PluginFlowNodes.<qualified>.impl(...)` for every
/// `CustomNode`, so the shim must expose a `PluginFlowNodes` block whose
/// decl names + `resolve`/`sanitizeModuleIdent` helpers are byte-identical
/// to main.zig's — otherwise the flow file fails to compile with
/// `struct 'game' has no member named 'PluginFlowNodes'`. The block is
/// emitted only when at least one node was discovered: with no flow nodes
/// no flow file references `game.PluginFlowNodes`, so the empty `struct {}`
/// shell would be dead weight (and game-script nodes additionally need the
/// named-module wiring in build.zig — Gap 2 — which `root.zig:generate`
/// emits in lockstep).
pub const GameShimOptions = struct {
    /// Emit the `.labelle/tests/` shim (labelle-assembler#275): `Game`
    /// instantiated over the project's real ECS backend instead of the
    /// default `engine.Game` re-export. `ecs` selects which backend the
    /// shim declares as `EcsBackend`.
    is_tests_target: bool = false,
    /// The project's configured ECS choice — only consulted when
    /// `is_tests_target` is set, to pick `@import("ecs_backend")` (real
    /// adapter) vs `engine.MockEcsBackend(u32)`.
    ecs: config.EcsChoice = .mock,
    /// Discovered-but-unconsumed plugin events (labelle-assembler#630).
    /// The `plugin_events` positional arg carries only the CONSUMED
    /// entries; this list carries the elided remainder so the shim's
    /// `PluginEvents` block stays byte-identical to main.zig's
    /// (including the `// elided (no consumer): <tag>` comments).
    /// Defaults empty for callers that never filter.
    plugin_events_elided: []const main_zig.PluginEvent = &.{},
};

pub fn generateGameShim(
    allocator: std.mem.Allocator,
    plugin_events: []const main_zig.PluginEvent,
    plugin_flow_nodes: []const main_zig.PluginFlowNode,
    opts: GameShimOptions,
) ![]u8 {
    var aw: std.Io.Writer.Allocating = .init(allocator);
    errdefer aw.deinit();
    const w = &aw.writer;

    if (opts.is_tests_target) {
        // labelle-assembler#275 — the tests target instantiates `Game`
        // over the real ECS backend so plugin systems compile + run
        // headless. The `EcsBackend` decl varies by ECS choice; the
        // rest of the prelude (stubs, `Game`, `EntityId`) is shared.
        try w.writeAll(game_shim_tests_prelude_header);
        if (opts.ecs == .mock) {
            try w.writeAll("const EcsBackend = engine.MockEcsBackend(u32);\n");
        } else {
            // The same module the plugins resolve via `@import("ecs_backend")`
            // (wired by `tests_ecs_import` in the generated build.zig), so the
            // test game's `ecs_backend` and the plugins' iterators share a type.
            try w.writeAll("const EcsBackend = @import(\"ecs_backend\");\n");
        }
        try w.writeAll(game_shim_tests_prelude_body);
    } else {
        try w.writeAll(game_shim_prelude);
    }

    if (plugin_events.len > 0 or plugin_flow_nodes.len > 0) {
        // Dispatch through a minimal `Codegen` context so the shim's
        // emission path matches the orchestrator's — `writePluginEventsBlock`
        // / `writePluginFlowNodesBlock` are mixin methods that read
        // `self.plugin_events` / `self.plugin_flow_nodes`. Mirrors
        // `main_template.zig`'s `ctx.writePluginXxxBlock(bw)` calls so the
        // shim's blocks are bit-identical to the ones emitted into main.zig.
        var ctx: main_zig.Codegen = .{
            .allocator = allocator,
            .cfg = .{ .name = "", .ecs = .mock },
            .script_entries = &.{},
            .prefab_names = &.{},
            .jsonc_scene_names = &.{},
            .scene_manifests = &.{},
            .component_names = &.{},
            .hook_names = &.{},
            .event_names = &.{},
            .enum_names = &.{},
            .view_names = &.{},
            .gizmo_names = &.{},
            .animation_names = &.{},
            .plugin_events = plugin_events,
            .plugin_flow_nodes = plugin_flow_nodes,
            .plugin_pin_styles = &.{},
            .plugin_coercions = &.{},
            .plugin_events_elided = opts.plugin_events_elided,
        };
        if (plugin_events.len > 0) try ctx.writePluginEventsBlock(w);
        // Gap 1 — surface `PluginFlowNodes` so flow files'
        // `@import("game").PluginFlowNodes.<qualified>.impl(...)` resolves.
        // Game-script nodes inside this block reference named modules
        // (`@import("script__<sanitized>")`); the matching
        // `overrideImport(game_mod, "script__<sanitized>", ...)` in
        // `build_files.generateBuildZig` makes them resolvable from the
        // `game` module.
        if (plugin_flow_nodes.len > 0) try ctx.writePluginFlowNodesBlock(w);
    }

    var arr_list = aw.toArrayList();
    // `toArrayList` resets the writer, so `aw.deinit` (the errdefer above)
    // is now a no-op and `arr_list` owns the buffer — guard it so an OOM in
    // `toOwnedSlice` frees the buffer instead of leaking it.
    errdefer arr_list.deinit(allocator);
    return arr_list.toOwnedSlice(allocator);
}

// ── Regression: no leak-on-OOM in the final toOwnedSlice (#540) ──────
//
// `aw.toArrayList()` resets the writer and hands the accumulated buffer
// to `arr_list`; the function-scope `errdefer aw.deinit()` then covers
// nothing. If the trailing `arr_list.toOwnedSlice(allocator)` OOMs, the
// buffer leaked until an `errdefer arr_list.deinit(allocator)` was added.
//
// Drive `generateGameShim` through a `FailingAllocator` forced to fail at
// each allocation index and assert the freed/allocated tally balances at
// every point.
test "generateGameShim: no allocator leak at any OOM point" {
    const flow_nodes = [_]main_zig.PluginFlowNode{
        .{
            .module_import_path = "flows/counter.zig",
            .module_sanitized = "flows_s_counter",
            .node_name = "tick",
            .is_script = true,
        },
    };

    const total_allocs = blk: {
        var fa = std.testing.FailingAllocator.init(std.testing.allocator, .{});
        const shim = try generateGameShim(fa.allocator(), &.{}, &flow_nodes, .{});
        fa.allocator().free(shim);
        break :blk fa.alloc_index;
    };

    var i: usize = 0;
    while (i < total_allocs) : (i += 1) {
        var fa = std.testing.FailingAllocator.init(std.testing.allocator, .{ .fail_index = i });
        if (generateGameShim(fa.allocator(), &.{}, &flow_nodes, .{})) |shim| {
            fa.allocator().free(shim);
        } else |err| {
            // `std.Io.Writer` maps allocator failures to WriteFailed;
            // either surfaces the OOM, both are non-leaking failure paths.
            try std.testing.expect(err == error.OutOfMemory or err == error.WriteFailed);
        }
        try std.testing.expectEqual(fa.allocated_bytes, fa.freed_bytes);
    }
}
