//! `FontBackendAdapter` COMPILE + RUN acceptance (labelle-assembler#700).
//!
//! `test/backend_wiring_tests.zig` already pins the emitted strings for the
//! font block — and that family of test is exactly what let #700 through for
//! the whole life of the feature. Every one of those asserts passed while
//! declaring a single `.font` resource in `project.labelle` failed to compile
//! on EVERY assembler + engine pairing ever released:
//!
//!   main.zig: error: expected type '*const fn ([:0]const u8, []const u8,
//!     assets.loaders.font.FontBakeParams, mem.Allocator) T',
//!   found '*const fn ([:0]const u8, []const u8, ?*const anyopaque,
//!     mem.Allocator) T'
//!       .decode = FontBackendAdapter.decode,
//!
//! A string pin cannot see that, because the emitted text was internally
//! consistent — it just did not satisfy `engine.FontBackend`. So this suite
//! takes the #586 / #691 / i18n-sentinel route instead: it renders the REAL
//! block through `writeFontBackendWiring`, splices it into a harness beside
//! a stub `engine` and a stub `BackendGfx`, and drives `zig test` on it
//! through the `test_options.zig_exe` seam. The generated bytes are compiled
//! and RUN; a signature regression is a compile error inside the harness and
//! therefore a failing test here.
//!
//! ## What the stubs mirror, and why hand-mirroring is safe here
//!
//! The assembler takes no dependency on labelle-engine, so the harness cannot
//! `@import` the real thing without a network fetch (the suite's hermeticity
//! rule). The two stubs are therefore transcriptions:
//!
//!   * `engine.zig` mirrors labelle-engine `src/assets/loaders/font.zig` —
//!     `FontBakeParams`, `CodepointRange`, `DecodedFont`, `FontId`, and the
//!     `FontBackend` vtable with `decode` taking `FontBakeParams` BY VALUE.
//!     That shape is not a guess: `FontBackend` was born typed in
//!     labelle-engine#529 (commit c7b6fcb, first released in engine v1.36.0)
//!     and every later commit touching that file keeps it, verified through
//!     v2.15.0. Engines older than v1.36.0 have no `FontLoader.setBackend`
//!     at all, so v1.36.0 is the hard floor for a `.font` resource and
//!     there is exactly ONE signature to satisfy above it.
//!   * `backend.zig` mirrors `backends/sokol/src/gfx/font.zig` — an `extern
//!     struct` `CodepointRange` and a `decodeFont` taking
//!     `*const FontBakeParams`.
//!
//! ## The two backends
//!
//! Both shapes that ship today are covered:
//!
//!   * a FONT-CAPABLE backend (sokol): the adapter must typecheck AND the
//!     marshal must actually carry the values across — the stub echoes the
//!     params it received back through `DecodedFont` so the test asserts on
//!     the bridged `pixel_height` / `ranges` / atlas dims rather than on the
//!     mere fact that it compiled. `CodepointRange` crosses a plain-struct →
//!     `extern struct` boundary, so it needs a real element-by-element copy;
//!     a `@ptrCast` there would be undefined.
//!   * a FONT-LESS backend (bgfx, which declares no font decls whatsoever):
//!     the `@hasDecl` guards must keep the whole marshal comptime-dead, so
//!     the block still compiles and `decode` reports
//!     `error.FontBackendNotImplemented`.

const std = @import("std");
const zspec = @import("zspec");
const generate = @import("generator");
const h = @import("helpers.zig");
const test_options = @import("test_options");

const io = std.testing.io;

test {
    zspec.runAll(@This());
}

fn writeFileIn(dir: std.Io.Dir, rel: []const u8, body: []const u8) !void {
    if (std.fs.path.dirname(rel)) |sub| try dir.createDirPath(io, sub);
    var f = try dir.createFile(io, rel, .{});
    defer f.close(io);
    try f.writeStreamingAll(io, body);
}

/// Render the shipped font wiring block exactly as `buildSetupCode` /
/// `buildCallbackInitCode` do (same 4-space indent).
fn renderFontWiring(allocator: std.mem.Allocator) ![]u8 {
    var alloc_writer: std.Io.Writer.Allocating = .init(allocator);
    errdefer alloc_writer.deinit();
    var ctx = h.emptyCodegen(allocator);
    try ctx.writeFontBackendWiring(&alloc_writer.writer, "    ");
    return alloc_writer.toOwnedSlice();
}

/// Transcription of labelle-engine `src/assets/loaders/font.zig` (v2.15.0;
/// unchanged in shape since v1.36.0). `FontBackend.decode` takes
/// `FontBakeParams` BY VALUE — the type-erased `?*const anyopaque` lives one
/// level up on the catalog's `WorkRequest.params`, and the engine casts it
/// back BEFORE calling the adapter.
const engine_stub =
    \\const std = @import("std");
    \\
    \\pub const CodepointRange = struct {
    \\    first: u32,
    \\    last: u32,
    \\};
    \\
    \\pub const FontBakeParams = struct {
    \\    pixel_height: f32 = 16.0,
    \\    ranges: []const CodepointRange = &.{},
    \\    atlas_width: u32 = 512,
    \\    atlas_height: u32 = 512,
    \\};
    \\
    \\pub const Glyph = extern struct {
    \\    x0: u16 = 0,
    \\    y0: u16 = 0,
    \\    x1: u16 = 0,
    \\    y1: u16 = 0,
    \\    xoff: f32 = 0,
    \\    yoff: f32 = 0,
    \\    advance: f32 = 0,
    \\};
    \\
    \\pub const CodepointEntry = extern struct {
    \\    codepoint: u32 = 0,
    \\    glyph_index: u32 = 0,
    \\};
    \\
    \\pub const KernPair = extern struct {
    \\    first: u32 = 0,
    \\    second: u32 = 0,
    \\    advance: f32 = 0,
    \\};
    \\
    \\pub const FontId = struct {
    \\    index: u16,
    \\    generation: u16,
    \\};
    \\
    \\pub const DecodedFont = struct {
    \\    bitmap: []u8,
    \\    width: u32,
    \\    height: u32,
    \\    glyphs: []Glyph,
    \\    codepoint_index: []const CodepointEntry,
    \\    ascent: f32,
    \\    descent: f32,
    \\    line_gap: f32,
    \\    line_height: f32,
    \\    kerning: []const KernPair,
    \\};
    \\
    \\pub const FontBackend = struct {
    \\    decode: *const fn (
    \\        file_type: [:0]const u8,
    \\        data: []const u8,
    \\        params: FontBakeParams,
    \\        allocator: std.mem.Allocator,
    \\    ) anyerror!DecodedFont,
    \\    upload: *const fn (decoded: DecodedFont) anyerror!FontId,
    \\    unload: *const fn (id: FontId) void,
    \\};
    \\
    \\pub const FontLoader = struct {
    \\    var active: ?FontBackend = null;
    \\    pub fn setBackend(b: FontBackend) void {
    \\        active = b;
    \\    }
    \\    pub fn currentBackend() ?FontBackend {
    \\        return active;
    \\    }
    \\};
;

/// Transcription of `backends/sokol/src/gfx/font.zig` — the font-capable
/// backend shape, MINUS `unloadFontAtlas` — the plain and registry-aware
/// variants below append their own so the registry one can timestamp the
/// atlas destruction. `decodeFont` ECHOES the marshalled params back through
/// `DecodedFont` so the test can prove the bridge carried real values.
const backend_font_core =
    \\const std = @import("std");
    \\
    \\pub const CodepointRange = extern struct {
    \\    first: u32,
    \\    last: u32,
    \\};
    \\
    \\pub const FontBakeParams = struct {
    \\    pixel_height: f32 = 16,
    \\    ranges: []const CodepointRange = &.{.{ .first = 0x20, .last = 0x7F }},
    \\    atlas_width: u32 = 512,
    \\    atlas_height: u32 = 512,
    \\};
    \\
    \\pub const Glyph = extern struct {
    \\    x0: u16 = 0,
    \\    y0: u16 = 0,
    \\    x1: u16 = 0,
    \\    y1: u16 = 0,
    \\    xoff: f32 = 0,
    \\    yoff: f32 = 0,
    \\    advance: f32 = 0,
    \\};
    \\
    \\pub const CodepointEntry = extern struct {
    \\    codepoint: u32 = 0,
    \\    glyph_index: u32 = 0,
    \\};
    \\
    \\pub const KernPair = extern struct {
    \\    first: u32 = 0,
    \\    second: u32 = 0,
    \\    advance: f32 = 0,
    \\};
    \\
    \\pub const FontAtlas = struct { texture: u32 };
    \\
    \\pub const DecodedFont = struct {
    \\    bitmap: []u8,
    \\    width: u32,
    \\    height: u32,
    \\    glyphs: []Glyph,
    \\    codepoint_index: []const CodepointEntry,
    \\    ascent: f32,
    \\    descent: f32,
    \\    line_gap: f32,
    \\    line_height: f32,
    \\    kerning: []const KernPair,
    \\};
    \\
    \\pub fn decodeFont(
    \\    file_type: [:0]const u8,
    \\    data: []const u8,
    \\    params: *const FontBakeParams,
    \\    allocator: std.mem.Allocator,
    \\) !DecodedFont {
    \\    _ = file_type;
    \\    _ = data;
    \\    // Echo the bridged values back out: atlas dims and pixel height
    \\    // ride the numeric fields, and the LAST codepoint range's bounds
    \\    // ride the vertical metrics. If the ranges bridge dropped or
    \\    // garbled an element these come back wrong, which is the point —
    \\    // typechecking alone would not catch it.
    \\    const last = params.ranges[params.ranges.len - 1];
    \\    return .{
    \\        .bitmap = try allocator.alloc(u8, params.ranges.len),
    \\        .width = params.atlas_width,
    \\        .height = params.atlas_height,
    \\        .glyphs = try allocator.alloc(Glyph, 0),
    \\        .codepoint_index = try allocator.alloc(CodepointEntry, 0),
    \\        .ascent = @floatFromInt(last.first),
    \\        .descent = @floatFromInt(last.last),
    \\        .line_gap = 0,
    \\        .line_height = params.pixel_height,
    \\        .kerning = try allocator.alloc(KernPair, 0),
    \\    };
    \\}
    \\
    \\pub fn uploadFontAtlas(decoded: DecodedFont) !FontAtlas {
    \\    return .{ .texture = decoded.width };
    \\}
;

/// A font-capable backend that has NOT opted into the registry seam — the
/// sokol/bgfx shape today. Every `registerCatalogFont` reference the adapter
/// emits must stay comptime-dead here.
const backend_with_fonts = backend_font_core ++
    \\
    \\pub fn unloadFontAtlas(atlas: FontAtlas) void {
    \\    _ = atlas;
    \\}
;

/// The shape a backend takes once it opts into the catalog font registry
/// (labelle-bgfx#85): `backend_with_fonts` plus the
/// `registerCatalogFont` / `unregisterCatalogFont` pair, recording what it
/// was handed and WHEN, so the test can assert on the handle arithmetic and
/// on the register-before-destroy ordering rather than on mere compilation.
const registry_decls =
    \\
    \\pub var register_count: u32 = 0;
    \\pub var last_registered_handle: u32 = 0;
    \\pub var last_registered_atlas: ?FontAtlas = null;
    \\pub var last_unregistered_handle: u32 = 0;
    \\pub var seq: u32 = 0;
    \\pub var registered_at: u32 = 0;
    \\pub var unregistered_at: u32 = 0;
    \\pub var destroyed_at: u32 = 0;
    \\
    \\pub fn registerCatalogFont(handle: u32, atlas: FontAtlas) void {
    \\    register_count += 1;
    \\    last_registered_handle = handle;
    \\    last_registered_atlas = atlas;
    \\    seq += 1;
    \\    registered_at = seq;
    \\}
    \\
    \\pub fn unregisterCatalogFont(handle: u32) void {
    \\    last_unregistered_handle = handle;
    \\    seq += 1;
    \\    unregistered_at = seq;
    \\}
    \\
    \\pub fn noteDestroy() void {
    \\    seq += 1;
    \\    destroyed_at = seq;
    \\}
;

/// `unloadFontAtlas` that timestamps the atlas destruction, so the test can
/// assert the registry entry is retired STRICTLY BEFORE the GPU atlas dies.
const registry_unload =
    \\
    \\pub fn unloadFontAtlas(atlas: FontAtlas) void {
    \\    _ = atlas;
    \\    noteDestroy();
    \\}
;

/// Font-capable backend that has opted into the registry seam.
const backend_with_font_registry = backend_font_core ++ registry_decls ++ registry_unload;

/// The bgfx shape: a graphics backend with NO font decls at all — not even
/// `FontAtlas`. Every reference the adapter makes to a font type must stay
/// behind a comptime-false `@hasDecl` guard, or a project that merely
/// declares a font resource stops compiling on this backend.
const backend_without_fonts =
    \\pub const nothing_here = {};
;

/// Harness: the REAL emitted block spliced into a function, plus tests that
/// exercise the installed vtable.
fn harnessSource(allocator: std.mem.Allocator, block: []const u8, extra_tests: []const u8) ![]u8 {
    return std.fmt.allocPrint(allocator,
        \\const std = @import("std");
        \\const engine = @import("engine.zig");
        \\const BackendGfx = @import("backend.zig");
        \\
        \\fn wire() void {{
        \\{s}
        \\}}
        \\
        \\{s}
    , .{ block, extra_tests });
}

const capable_tests =
    \\test "the adapter satisfies engine.FontBackend and bridges FontBakeParams" {
    \\    wire();
    \\    const b = engine.FontLoader.currentBackend().?;
    \\    const ranges = [_]engine.CodepointRange{
    \\        .{ .first = 0x20, .last = 0x7F },
    \\        .{ .first = 0x400, .last = 0x450 },
    \\    };
    \\    const alloc = std.testing.allocator;
    \\    const decoded = try b.decode("ttf", "fake-ttf-bytes", .{
    \\        .pixel_height = 24,
    \\        .ranges = &ranges,
    \\        .atlas_width = 256,
    \\        .atlas_height = 128,
    \\    }, alloc);
    \\    defer alloc.free(decoded.bitmap);
    \\    defer alloc.free(decoded.glyphs);
    \\    defer alloc.free(decoded.codepoint_index);
    \\    defer alloc.free(decoded.kerning);
    \\
    \\    try std.testing.expectEqual(@as(u32, 256), decoded.width);
    \\    try std.testing.expectEqual(@as(u32, 128), decoded.height);
    \\    try std.testing.expectEqual(@as(f32, 24), decoded.line_height);
    \\    // Both ranges arrived, and the last one's bounds survived the
    \\    // plain-struct -> extern-struct element copy.
    \\    try std.testing.expectEqual(@as(usize, 2), decoded.bitmap.len);
    \\    try std.testing.expectEqual(@as(f32, 0x400), decoded.ascent);
    \\    try std.testing.expectEqual(@as(f32, 0x450), decoded.descent);
    \\}
    \\
    \\test "upload/unload round-trip through the slot table" {
    \\    wire();
    \\    const b = engine.FontLoader.currentBackend().?;
    \\    const id = try b.upload(.{
    \\        .bitmap = &.{},
    \\        .width = 7,
    \\        .height = 1,
    \\        .glyphs = &.{},
    \\        .codepoint_index = &.{},
    \\        .ascent = 0,
    \\        .descent = 0,
    \\        .line_gap = 0,
    \\        .line_height = 0,
    \\        .kerning = &.{},
    \\    });
    \\    try std.testing.expectEqual(@as(u16, 1), id.generation);
    \\    b.unload(id);
    \\}
;

/// The whole point of the change: the id this adapter mints must reach the
/// backend paired with the atlas, keyed by the SAME number the draw seam
/// will hand back.
///
/// Only one test lives in this harness so the slot allocator is
/// deterministic — the first upload always lands in slot 0, which makes the
/// packed handle an exact literal (`0x0001_0000`: index 0 low, generation 1
/// high) rather than something recomputed from the value under test.
const registry_tests =
    \\test "upload registers the packed handle + atlas; unload retires it first" {
    \\    wire();
    \\    const b = engine.FontLoader.currentBackend().?;
    \\
    \\    try std.testing.expectEqual(@as(u32, 0), BackendGfx.register_count);
    \\    const id = try b.upload(.{
    \\        .bitmap = &.{},
    \\        .width = 7,
    \\        .height = 1,
    \\        .glyphs = &.{},
    \\        .codepoint_index = &.{},
    \\        .ascent = 0,
    \\        .descent = 0,
    \\        .line_gap = 0,
    \\        .line_height = 0,
    \\        .kerning = &.{},
    \\    });
    \\    try std.testing.expectEqual(@as(u16, 0), id.index);
    \\    try std.testing.expectEqual(@as(u16, 1), id.generation);
    \\
    \\    // Registered exactly once, with the atlas `uploadFontAtlas`
    \\    // returned (texture id echoes the decoded width, 7).
    \\    try std.testing.expectEqual(@as(u32, 1), BackendGfx.register_count);
    \\    try std.testing.expectEqual(@as(u32, 7), BackendGfx.last_registered_atlas.?.texture);
    \\
    \\    // The handle arithmetic must agree with labelle-engine#849's
    \\    // `packFontId`: index in the LOW 16 bits, generation in the HIGH
    \\    // 16. Slot 0 / generation 1 is 0x0001_0000 — a literal, so a
    \\    // packing that swapped the halves (0x0000_0001) or dropped the
    \\    // generation (0) fails here instead of coinciding.
    \\    try std.testing.expectEqual(@as(u32, 0x0001_0000), BackendGfx.last_registered_handle);
    \\    // ...and the slot index is recoverable by a plain @truncate, which
    \\    // is how a slot-keyed backend resolver reads it.
    \\    try std.testing.expectEqual(id.index, @as(u16, @truncate(BackendGfx.last_registered_handle)));
    \\
    \\    b.unload(id);
    \\    try std.testing.expectEqual(@as(u32, 0x0001_0000), BackendGfx.last_unregistered_handle);
    \\    // Retired BEFORE the GPU atlas was destroyed, so no draw can
    \\    // resolve a handle to dead state in between.
    \\    try std.testing.expect(BackendGfx.unregistered_at != 0);
    \\    try std.testing.expect(BackendGfx.destroyed_at != 0);
    \\    try std.testing.expect(BackendGfx.unregistered_at < BackendGfx.destroyed_at);
    \\}
;

const fontless_tests =
    \\test "a font-less backend still compiles and reports the gap at runtime" {
    \\    wire();
    \\    const b = engine.FontLoader.currentBackend().?;
    \\    try std.testing.expectError(
    \\        error.FontBackendNotImplemented,
    \\        b.decode("ttf", "fake-ttf-bytes", .{}, std.testing.allocator),
    \\    );
    \\}
;

/// Write the harness into `tmp` and drive `zig test` on it. Returns the
/// child's stderr on failure so the caller can surface the compile error.
fn runHarness(
    allocator: std.mem.Allocator,
    backend_src: []const u8,
    extra_tests: []const u8,
) !void {
    var tmp = std.testing.tmpDir(.{});
    defer tmp.cleanup();

    const block = try renderFontWiring(allocator);
    defer allocator.free(block);

    const harness = try harnessSource(allocator, block, extra_tests);
    defer allocator.free(harness);

    try writeFileIn(tmp.dir, "engine.zig", engine_stub);
    try writeFileIn(tmp.dir, "backend.zig", backend_src);
    try writeFileIn(tmp.dir, "harness.zig", harness);

    const cwd = try tmp.dir.realPathFileAlloc(io, ".", allocator);
    defer allocator.free(cwd);

    const result = try std.process.run(allocator, io, .{
        .argv = &.{ test_options.zig_exe, "test", "harness.zig" },
        .cwd = .{ .path = cwd },
    });
    defer allocator.free(result.stdout);
    defer allocator.free(result.stderr);

    const ok = result.term == .exited and result.term.exited == 0;
    if (!ok) {
        // `std.debug.print`, not `std.log.err`: Zig 0.16 fails any test that
        // emits a `log.err`, which would mask the real assertion below.
        std.debug.print("font adapter harness failed:\n{s}\n{s}\n", .{ result.stdout, result.stderr });
        return error.FontBackendAdapterDoesNotSatisfyVtable;
    }
}

pub const FONT_BACKEND_ADAPTER_COMPILES = struct {
    test "generated FontBackendAdapter installs into engine.FontBackend (font-capable backend)" {
        try runHarness(std.testing.allocator, backend_with_fonts, capable_tests);
    }

    test "generated FontBackendAdapter compiles against a backend with no font decls" {
        try runHarness(std.testing.allocator, backend_without_fonts, fontless_tests);
    }

    test "generated FontBackendAdapter registers the minted handle with a registry-aware backend" {
        try runHarness(std.testing.allocator, backend_with_font_registry, registry_tests);
    }
};
