//! Shared fixtures, templates, and helper functions for the split
//! `test/tests.zig` modules. See labelle-toolkit/labelle-assembler#184.
//!
//! Each per-domain test file imports this module and re-binds the few
//! decls it needs at module scope so test bodies stay terse.

const std = @import("std");
const generate = @import("generator");

// Engine codegen template (inlined for tests — normally loaded from engine's codegen/ directory)
pub const engine_template =
    \\/// Generated by labelle-cli — do not edit.
    \\const std = @import("std");
    \\const engine = @import("labelle-engine");
    \\const BackendGfx = @import("backend_gfx");
    \\const BackendInput = @import("backend_input");
    \\const BackendAudio = @import("backend_audio");
    \\const window = @import("backend_window");
    \\// Log sink (default: stderr). Override in project template to disable or customize.
    \\const LogSink = engine.core.StderrLogSink;
    \\{{#if ecs_mode_mock}}const EcsBackend = engine.MockEcsBackend(u32);
    \\{{#else}}const EcsAdapter = @import("ecs_backend");
    \\const EcsBackend = EcsAdapter;
    \\{{/if}}{{#if has_gui}}const GuiBackend = @import("gui_backend");
    \\{{#else}}const GuiBackend = engine.StubGui;
    \\{{/if}}{{hook_imports_block}}{{enum_imports_block}}{{jsonc_scene_block}}
    \\const gfx = @import("labelle-gfx");
    \\
    \\{{game_layers_block}}
    \\{{resource_registry_block}}const AllHookPayloads = engine.HookPayload(EcsBackend.Entity);
    \\
    \\{{game_hooks_block}}const Renderer = gfx.GfxRenderer(BackendGfx, GameLayers, EcsBackend.Entity);
    \\
    \\const AssembledGame = engine.GameConfig(
    \\    Renderer,
    \\    EcsBackend,
    \\    BackendInput,
    \\    BackendAudio,
    \\    GuiBackend,
    \\    *GameHooks,
    \\    LogSink,
    \\    Components,
    \\    DiscoveredGizmoCategories,
    \\);
    \\{{prefab_registry_block}}{{component_registry_block}}{{system_registry_block}}{{all_scripts_block}}const Scripts = engine.ScriptRegistry(AllScripts);
    \\
    \\{{#if has_context}}const GameContext = @import("scripts/context.zig").GameContext(EcsBackend);
    \\{{#else}}const GameContext = struct {};
    \\{{/if}}const Runner = engine.ScriptRunner(AllScripts, GameContext, EcsBackend);
    \\
    \\{{view_registry_block}}{{gizmo_registry_block}}{{animation_registry_block}}// Gizmo rendering is now handled by g.renderGizmos() — no generated code needed.
    \\// The engine delegates to the renderer's renderGizmoDraws() method.
    \\{{lifecycle}}
;

// Minimal lifecycle templates for testing (mustache format — no shared sections)
pub const raylib_lifecycle =
    \\const screen_w: u32 = {{width}};
    \\const screen_h: u32 = {{height}};
    \\const screen_title = "{{title}}";
    \\const target_fps: u32 = {{fps}};
    \\pub fn main() !void {
    \\    var gpa = std.heap.DebugAllocator(.{}).init;
    \\    const allocator = gpa.allocator();
    \\{{hidden_setup}}    var hooks = GameHooks{};
    \\    var g = AssembledGame.init(allocator);
    \\    g.setHooks(&hooks);
    \\    g.renderer.setScreenHeight(@as(f32, @floatFromInt(screen_h)));
    \\{{setup_code}}
    \\    while (!window.windowShouldClose()) {
    \\        const dt: f32 = 0.016;
    \\{{tick_code}}        g.tick(dt);
    \\        g.render();
    \\{{gui_draw_code}}    }
    \\}
    \\
;

pub const sokol_lifecycle =
    \\var g: AssembledGame = undefined;
    \\var hooks: GameHooks = .{};
    \\var gpa = std.heap.DebugAllocator(.{}).init;
    \\{{module_vars}}const screen_w: u32 = {{width}};
    \\const screen_h: u32 = {{height}};
    \\const screen_title = "{{title}}";
    \\const target_fps: u32 = {{fps}};
    \\export fn init() callconv(.c) void {
    \\{{hidden_setup}}    const allocator = gpa.allocator();
    \\    g = AssembledGame.init(allocator);
    \\    g.setHooks(&hooks);
    \\    g.renderer.setScreenHeight(@as(f32, @floatFromInt(screen_h)));
    \\{{init_code}}}
    \\export fn frame() callconv(.c) void {
    \\    const dt: f32 = 0.016;
    \\{{tick_code}}    g.tick(dt);
    \\    g.render();
    \\{{gui_draw_code}}}
    \\export fn cleanup() callconv(.c) void {
    \\{{cleanup_code}}    g.deinit();
    \\    _ = gpa.deinit();
    \\}
    \\
;

// Mirror of `backends/null/templates/headless.txt` — the actual null
// backend's lifecycle template — trimmed to the placeholders the loop
// path emits. Used by the headless-runner tests below so the assertion
// surface matches the shape of the generated `main.zig` exactly without
// pulling in the file from disk.
pub const null_lifecycle =
    \\const screen_w: u32 = {{width}};
    \\const screen_h: u32 = {{height}};
    \\const screen_title = "{{title}}";
    \\const target_fps: u32 = {{fps}};
    \\
    \\{{module_vars}}
    \\fn getMaxFrames(_: std.mem.Allocator) u32 {
    \\    const raw_c = std.c.getenv("LABELLE_NULL_FRAMES") orelse return 5;
    \\    const raw = std.mem.span(raw_c);
    \\    return std.fmt.parseInt(u32, raw, 10) catch 5;
    \\}
    \\
    \\pub fn main() !void {
    \\    var gpa = std.heap.DebugAllocator(.{}).init;
    \\    defer _ = gpa.deinit();
    \\    const allocator = gpa.allocator();
    \\{{hooks_init_block}}
    \\    var g = AssembledGame.init(allocator);
    \\    defer g.deinit();
    \\    g.setHooks(&hooks);
    \\    g.setScreenHeight(@as(f32, @floatFromInt(screen_h)));
    \\    g.getCamera().setPosition(0, @as(f32, @floatFromInt(screen_h)));
    \\{{preview_setup}}{{setup_code}}
    \\    const max_frames = getMaxFrames(allocator);
    \\    const dt: f32 = 1.0 / 60.0;
    \\    var frame: u32 = 0;
    \\    while (frame < max_frames) : (frame += 1) {
    \\{{preview_heartbeat}}{{tick_code}}        g.tick(dt);
    \\{{gui_draw_code}}    }
    \\}
    \\
;

// Mirror of `backends/sokol/templates/desktop.txt` — the actual sokol+wasm
// template — but trimmed to just the bits that matter for verifying the
// allocator-shadow fix (labelle-cli#198). Module-scope emits
// `{{allocator_decl}}` and `initInner` emits `{{allocator_local_decl}}`
// (empty on wasm, `const allocator = gpa.allocator();` on desktop). The
// regression we're guarding against is *two* `const allocator =` lines
// in the same generated file for sokol+wasm.
pub const sokol_alloc_lifecycle =
    \\var g: AssembledGame = undefined;
    \\{{hooks_init_block}}
    \\{{allocator_decl}}
    \\{{module_vars}}
    \\fn initInner() !void {
    \\{{allocator_local_decl}}{{init_code}}}
    \\export fn init() callconv(.c) void {
    \\    g = AssembledGame.init({{allocator_expr}});
    \\    initInner() catch unreachable;
    \\}
    \\export fn cleanup() callconv(.c) void {
    \\{{cleanup_code}}    g.deinit();
    \\{{allocator_cleanup}}}
    \\
;

pub const empty_names: []const []const u8 = &.{};
pub const ScriptEntry = generate.script_scanner.ScriptScanner.ScriptEntry;
pub const empty_entries: []const ScriptEntry = &.{};
pub const SceneManifest = generate.scene_manifest.SceneManifest;
pub const empty_scene_manifests: []const SceneManifest = &.{};
pub const PluginEvent = generate.main_zig.PluginEvent;
pub const empty_plugin_events: []const PluginEvent = &.{};
pub const PluginFlowNode = generate.main_zig.PluginFlowNode;
pub const empty_plugin_flow_nodes: []const PluginFlowNode = &.{};
pub const PluginPinStyle = generate.main_zig.PluginPinStyle;
pub const empty_plugin_pin_styles: []const PluginPinStyle = &.{};
pub const PluginCoercion = generate.main_zig.PluginCoercion;
pub const empty_plugin_coercions: []const PluginCoercion = &.{};

/// Helper: create global ScriptEntry values from a list of names (for testing).
/// Names are treated as filenames like "foo.zig" (no prefix, no state).
pub fn GlobalEntries(comptime names: []const []const u8) type {
    return struct {
        const entries = init: {
            var e: [names.len]ScriptEntry = undefined;
            for (names, 0..) |name, i| {
                e[i] = .{
                    .name = name,
                    .filename = name ++ ".zig",
                    .states = &.{},
                    .sort_order = null,
                    .subdir = null,
                    .rel_path = name ++ ".zig",
                };
            }
            break :init e;
        };
        const slice: []const ScriptEntry = &entries;
    };
}
pub fn globalEntries(comptime names: []const []const u8) []const ScriptEntry {
    return GlobalEntries(names).slice;
}

// Helper: create a ResolvedGui for testing (render_interface, no bridge)
pub fn testGuiRenderInterface(name: []const u8) generate.ResolvedGui {
    return .{
        .name = name,
        .rendering = .render_interface,
        .plugin_dir = "/fake/gui/plugin",
    };
}

/// Construct a minimal `Codegen` context with every field empty. Used
/// by tests that exercise a single mixin method whose body reads no
/// state from `self` (e.g. the asset-wiring writers — they just take a
/// writer + indent). Mirrors what the production orchestrator hands
/// `generateMainZigFromTemplate`, just with empty slices.
pub fn emptyCodegen(allocator: std.mem.Allocator) generate.main_zig.Codegen {
    return .{
        .allocator = allocator,
        .cfg = .{ .name = "test-game", .ecs = .mock },
        .script_entries = &.{},
        .prefab_names = &.{},
        .jsonc_scene_names = &.{},
        .scene_manifests = &.{},
        .component_names = &.{},
        .hook_names = &.{},
        .event_names = &.{},
        .enum_names = &.{},
        .view_names = &.{},
        .gizmo_names = &.{},
        .animation_names = &.{},
        .plugin_events = &.{},
        .plugin_flow_nodes = &.{},
        .plugin_pin_styles = &.{},
        .plugin_coercions = &.{},
    };
}

// Helper: create a ResolvedGui for testing (raw_backend with lifecycle + bridge)
pub fn testGuiRawBackend(name: []const u8) generate.ResolvedGui {
    return .{
        .name = name,
        .rendering = .raw_backend,
        .lifecycle = .{ .init = true, .shutdown = true },
        .plugin_dir = "/fake/gui/plugin",
        .bridge_dir = "/fake/gui/bridge",
    };
}
