//! Manifest **v2** desktop codegen splice (epic #453 item 3, PR 3 — see
//! `docs/design/manifest-v2-build-graph.md` §3/§5/§7). This is the codegen half
//! of manifest-v2: it renders a project's backend-dep + link wiring from a typed,
//! declarative `BackendManifestV2` (PR 1) instead of the v1 raw-text fragments.
//!
//! Gated in `build_files.zig` on `manifest_version >= 2` (via
//! `manifest_v2.parseManifest`): a v1 (or field-less) manifest keeps the existing
//! `manifest_splice` + enum path byte-unchanged; only a v2 manifest reaches here.
//! PR 3 wires only the DESKTOP platform entry (the byte anchor); other platforms
//! land in PRs 5/6/7 with the hook phases + shared packager.
//!
//! ## The desktop byte anchor (§7) — why this reproduces the exact enum/v1 text
//!
//! §7 makes the sokol-desktop cell the ONE hard enum-vs-v2 0-diff anchor: "the v2
//! path can be emitted so it reproduces that exact text (unrolling the walk's
//! output for the desktop case)". So the DECLARATIVE lines the v2 model owns —
//! the `b.dependency` literal (dep name + the base↔per-platform `dep_options`
//! merge, each value from the closed `ValueSource` predicate set), the provider
//! `.module(...)` decls (honoring `root_alias`), the `.artifact(...)` decls, and
//! the `linkLibrary`/framework wiring — are GENERATED here from the manifest, and
//! this generated output is what proves the v2 data reproduces the baseline
//! option/module/artifact set byte-for-byte.
//!
//! The NON-declarative residual the v2 model deliberately does NOT carry — the
//! backend-specific prose comments (#140/#271/#258/#121) and the two hand-written
//! core-diamond `overrideImport` `if`-blocks (classified **CORE** in §2, destined
//! for the generic `core_diamond.unifyCoreDiamond` walk) — is emitted here as
//! VERBATIM anchor residual (`anchor_head_comment`/`anchor_tail_overrides`/
//! `anchor_link_body`, generated byte-exactly from the retained fixture
//! fragments). This is precisely §7's "unrolling the walk's output for the desktop
//! case": the desktop cell keeps the unrolled override statements (not the generic
//! walk call) so the anchor hits 0-diff. Splicing the generic
//! `core_diamond.generated_walk_zig` here INSTEAD would change the generated text
//! (a walk call + helper def ≠ the unrolled `if`-blocks) and break the 0-diff
//! anchor — so it is intentionally NOT spliced on the desktop path. The generic
//! walk stays validated by PR 2's tests + `emitCoreDiamondWalk` below (a drift
//! guard) and is the mechanism the golden-snapshot cells (PR 5+) use, where the
//! gate is a reviewed golden — not byte-identity — exactly because a loop emits
//! different source than the unrolled form (§7 tier-1).
//!
//! When the enum path is deleted (§6 step 5 / PR 12) the anchor's baseline is
//! gone, the desktop cell becomes a golden snapshot too, and this verbatim
//! residual is deleted with the v1 fragments it mirrors.

const std = @import("std");
const config = @import("../config.zig");
const manifest_v2 = @import("manifest_v2.zig");
const core_diamond = @import("core_diamond.zig");
const packager = @import("packager.zig");
const backend_registry = @import("../backend_registry.zig");

const BackendManifestV2 = manifest_v2.BackendManifestV2;
const DepOption = BackendManifestV2.DepOption;
const ProjectConfig = config.ProjectConfig;

// ── Closed dependency-option value predicate set (design §4) ──────────────
// Names are declarative manifest data; VALUES come from this closed predicate
// set the assembler computes — the EXACT `paramValue` predicates the v1 splice
// uses today (`manifest_splice.zig:272`-`289`), plus the literal true/false the
// mobile `dont_link_system_libs` flag needs. The result is the literal `"true"`/
// `"false"` rendered into the generated `b.dependency` options struct.
fn depOptionValue(vs: DepOption.ValueSource, cfg: ProjectConfig) []const u8 {
    return switch (vs) {
        // with_imgui / gui_enabled: true iff the resolved gui plugin is imgui.
        .gui_is_imgui => if (cfg.resolved_gui) |gui|
            (if (std.mem.eql(u8, gui.name, "imgui")) "true" else "false")
        else
            "false",
        .gamepad_enabled => if (cfg.gamepad == .auto) "true" else "false",
        .gamepad_hidapi => if (cfg.gamepad_hidapi) "true" else "false",
        .true_literal => "true",
        .false_literal => "false",
    };
}

/// The base↔per-platform `dep_options` merge (design §3/§4 merge contract): start
/// from the base list, then for each per-platform entry OVERRIDE a base entry of
/// the same `name` (per-platform value wins) or APPEND it. No subtractive form.
/// Returns an allocator-owned slice the caller frees. Order is base entries first
/// (in declaration order), then per-platform appends — matching the enum-path
/// `b.dependency` literal order.
fn mergeDepOptions(
    allocator: std.mem.Allocator,
    base: []const DepOption,
    per_platform: []const DepOption,
) ![]DepOption {
    var out: std.ArrayList(DepOption) = .empty;
    errdefer out.deinit(allocator);
    for (base) |b| try out.append(allocator, b);
    for (per_platform) |p| {
        var overridden = false;
        for (out.items) |*existing| {
            if (std.mem.eql(u8, existing.name, p.name)) {
                existing.value = p.value; // override-by-name
                overridden = true;
                break;
            }
        }
        if (!overridden) try out.append(allocator, p); // append
    }
    return out.toOwnedSlice(allocator);
}

/// Root import alias for a provider module: `root_alias` if declared, else the
/// default `backend_<name>` (design §3 `ModuleDecl.root_alias`). Caller owns the
/// returned slice.
fn moduleAlias(allocator: std.mem.Allocator, mod: BackendManifestV2.ModuleDecl) ![]const u8 {
    if (mod.root_alias) |a| return allocator.dupe(u8, a);
    return std.fmt.allocPrint(allocator, "backend_{s}", .{mod.name});
}

/// Emit the generic core+gfx-diamond walk helper (`core_diamond.generated_walk_zig`)
/// into the generated build.zig. NOT used on the desktop byte-anchor path (which
/// unrolls — see the module doc); this is the spliceable mechanism for the
/// golden-snapshot cells (PR 5+) and a compile/drift guard that keeps this module
/// referencing the PR-2 walk source.
pub fn emitCoreDiamondWalk(w: anytype) !void {
    try w.writeAll(core_diamond.generated_walk_zig);
}

/// v2 replacement for the backend-dep enum branch (`renderSection(.., "backend_<tag>")`)
/// / the v1 `renderBackendDepSection`. Dispatches on the target platform: DESKTOP
/// (PR 3, byte anchor) and ANDROID (PR 5, golden cell); other platforms land in
/// later PRs.
pub fn renderBackendDepSectionV2(
    allocator: std.mem.Allocator,
    m: BackendManifestV2,
    cfg: ProjectConfig,
    w: anytype,
) !void {
    switch (cfg.platform) {
        .desktop => try renderDesktopBackendDepV2(allocator, m, cfg, w),
        .android => try renderAndroidBackendDepV2(allocator, m, cfg, w),
        .ios => try renderIosBackendDepV2(allocator, m, cfg, w),
        else => return error.V2PlatformUnsupported,
    }
}

/// DESKTOP backend-dep (PR 3 byte anchor). Generated from the manifest: the
/// `b.dependency` literal (dep name + merged `dep_options`), the `.module(...)`
/// decls (honoring `root_alias`), and the `.artifact(...)` decls. The surrounding
/// prose + unrolled core-diamond overrides are the anchor residual (module doc).
fn renderDesktopBackendDepV2(
    allocator: std.mem.Allocator,
    m: BackendManifestV2,
    cfg: ProjectConfig,
    w: anytype,
) !void {
    const desktop = m.platforms.desktop orelse return error.V2PlatformUnsupported;

    // HEAD: backend-specific provenance prose (not declarative). Anchor residual.
    try w.writeAll(anchor_head_comment);
    try w.writeByte('\n');

    // GENERATED: `const backend_dep = b.dependency("<dep_name>", .{ .target =
    // target, .optimize = optimize, <merged dep_options> });`
    const opts = try mergeDepOptions(allocator, m.dep_options, desktop.dep_options);
    defer allocator.free(opts);
    try w.print("    const backend_dep = b.dependency(\"{s}\", .{{ .target = target, .optimize = optimize", .{m.dep_name});
    for (opts) |opt| {
        try w.print(", .{s} = {s}", .{ opt.name, depOptionValue(opt.value, cfg) });
    }
    try w.writeAll(" });\n");

    // GENERATED: provider module decls under their root alias.
    for (m.modules) |mod| {
        const alias = try moduleAlias(allocator, mod);
        defer allocator.free(alias);
        try w.print("    const {s} = backend_dep.module(\"{s}\");\n", .{ alias, mod.name });
    }

    // GENERATED: artifact decls for this platform (the var name IS the artifact
    // name, matching the enum path: `const sokol_clib = backend_dep.artifact(...)`).
    for (desktop.artifacts) |art| {
        try w.print("    const {s} = backend_dep.artifact(\"{s}\");\n", .{ art.name, art.name });
    }

    // TAIL: the two unrolled core-diamond `overrideImport` `if`-blocks + prose.
    // Anchor residual — §7 "unrolling the walk's output for the desktop case".
    try w.writeAll(anchor_tail_overrides);
}

// ──────────────────────────────────────────────────────────────────────────
// ANDROID v2 emitters (PR 5, golden cell). Android is the first HOOK-BEARING
// conversion: `resolve_target` picks the ABI before any `b.dependency` and
// `post_wire` supplies the NDK-sysroot / addLibraryPath / libc.txt residual
// (design §4). The generated build.zig `@import`s the backend hook as a sibling
// `backend_build_hook.zig` and calls both phases. Unlike the desktop byte anchor,
// this is a GOLDEN cell (§7): the generated text legitimately DIFFERS from the
// enum `header_android`/`android_deps`/`backend_sokol_android`/`android_link`
// path — the residual moved into the imported hook and the unrolled core-diamond
// overrides became the generic `unifyCoreDiamond` loop. See docs §7 for why the
// text golden alone is blind to the hook body (hence the hook's own gates).
// ──────────────────────────────────────────────────────────────────────────

/// The root-import alias the generated build.zig references the backend hook by.
/// The assembler stages the manifest's `build_hook` file next to the generated
/// `build.zig` under this name (see `stageBackendBuildHook`) so the generated
/// `@import("backend_build_hook.zig")` resolves at build time.
pub const hook_import_name = "backend_build_hook.zig";

/// Stage (copy) the backend package's `build_hook` file next to the generated
/// build.zig, under `hook_import_name`. The generated v2 (android, PR 5) build.zig
/// `@import`s the hook by that sibling name and calls `resolve_target`/`post_wire`;
/// without this copy a real v2 build fails at import resolution (PR #466 Finding 3).
/// Mirrors how the orchestrator writes the other generated siblings (build.zig,
/// game.zig, main.zig) into `target_dir`.
///
/// No-op (returns false) when the named manifest is v1 or carries no `build_hook`;
/// returns true when a hook was staged. `backend_manifest_name` is the SAME name the
/// caller passed to `generateBuildZig` (null there ⇒ the enum path, so the caller
/// should not invoke this).
pub fn stageBackendBuildHook(
    allocator: std.mem.Allocator,
    cfg: ProjectConfig,
    project_dir: []const u8,
    backend_manifest_name: []const u8,
    target_dir: []const u8,
) !bool {
    const parsed = try manifest_v2.loadNamedManifest(allocator, cfg, project_dir, backend_manifest_name);
    defer parsed.free(allocator);
    const m = switch (parsed) {
        .v1 => return false,
        .v2 => |v| v,
    };
    const hook_rel = m.build_hook orelse return false;

    const pkg_dir = try backend_registry.resolveBackendPackage(allocator, cfg, project_dir);
    defer allocator.free(pkg_dir);
    const src_path = try std.fs.path.join(allocator, &.{ pkg_dir, hook_rel });
    defer allocator.free(src_path);

    const io = config.globalIo();
    const cwd = std.Io.Dir.cwd();
    const content = try cwd.readFileAlloc(io, src_path, allocator, .limited(256 * 1024));
    defer allocator.free(content);

    var dir = try cwd.openDir(io, target_dir, .{});
    defer dir.close(io);
    const file = try dir.createFile(io, hook_import_name, .{});
    defer file.close(io);
    try file.writeStreamingAll(io, content);
    return true;
}

/// v2 android HEADER — replaces the enum `header_android` block. Instead of
/// inlining `getAndroidNdkSysroot`/`ndkHostTag` + the target-resolution block, it
/// imports the backend hook and resolves the android target via `resolve_target`
/// (design §4, runs BEFORE any `b.dependency`). The NDK sysroot is detected later,
/// inside `post_wire`.
pub fn renderAndroidHeaderV2(m: BackendManifestV2, w: anytype) !void {
    _ = m.platforms.android orelse return error.V2PlatformUnsupported;
    try w.print(
        \\const std = @import("std");
        \\
        \\const backend_build_hook = @import("{s}");
        \\
        \\pub fn build(b: *std.Build) void {{
        \\    const optimize = b.standardOptimizeOption(.{{}});
        \\
        \\    // resolve_target (design §4) — the backend hook picks the android ABI
        \\    // from -Demulator/-Dandroid_arch + host arch, BEFORE any b.dependency.
        \\    const android_target = backend_build_hook.resolve_target(b, .{{ .platform = .android }}).target;
        \\
        \\
    , .{hook_import_name});
}

/// v2 android core/gfx/engine dep decls — the declarative half of the enum
/// `android_deps` section, WITHOUT the unrolled `overrideImport` diamond +
/// `unifyGfxSubpackageCore` (those are replaced by the generic `unifyCoreDiamond`
/// walk emitted after the backend-dep section, design §5).
pub fn renderAndroidDepsDeclsV2(w: anytype) !void {
    try w.writeAll(
        \\    const core_dep = b.dependency("labelle_core", .{ .target = android_target, .optimize = optimize });
        \\    const core_mod = core_dep.module("labelle-core");
        \\
        \\    const gfx_dep = b.dependency("labelle_gfx", .{ .target = android_target, .optimize = optimize });
        \\    const gfx_mod = gfx_dep.module("labelle-gfx");
        \\
        \\    const engine_dep = b.dependency("engine", .{ .target = android_target, .optimize = optimize });
        \\    const engine_mod = engine_dep.module("engine");
        \\
        \\
    );
}

/// v2 android backend-dep — the generic `b.dependency` literal (`.target =
/// android_target`) + `.module(...)` decls (honoring `root_alias`) + `.artifact`
/// decls (with declarative `.pic`). Then the generic core-diamond walk CALLS
/// (design §5) rooted at gfx/engine + each backend module — replacing the enum
/// `android_deps` unrolled overrides. The NDK `addSystemIncludePath` residual is
/// NOT here; it is `post_wire`'s job (emitted in the link section).
fn renderAndroidBackendDepV2(
    allocator: std.mem.Allocator,
    m: BackendManifestV2,
    cfg: ProjectConfig,
    w: anytype,
) !void {
    const android = m.platforms.android orelse return error.V2PlatformUnsupported;

    // GENERATED: `const backend_dep = b.dependency("<dep_name>", .{ .target =
    // android_target, .optimize = optimize, <merged dep_options> });`
    const opts = try mergeDepOptions(allocator, m.dep_options, android.dep_options);
    defer allocator.free(opts);
    try w.print("    const backend_dep = b.dependency(\"{s}\", .{{ .target = android_target, .optimize = optimize", .{m.dep_name});
    for (opts) |opt| {
        try w.print(", .{s} = {s}", .{ opt.name, depOptionValue(opt.value, cfg) });
    }
    try w.writeAll(" });\n");

    // GENERATED: provider module decls under their root alias.
    for (m.modules) |mod| {
        const alias = try moduleAlias(allocator, mod);
        defer allocator.free(alias);
        try w.print("    const {s} = backend_dep.module(\"{s}\");\n", .{ alias, mod.name });
    }

    // GENERATED: artifact decls + declarative `.pic` (design §2 note 1).
    for (android.artifacts) |art| {
        try w.print("    const {s} = backend_dep.artifact(\"{s}\");\n", .{ art.name, art.name });
        if (art.pic) try w.print("    {s}.root_module.pic = true;\n", .{art.name});
    }

    // GENERATED: the generic core+gfx-diamond walk CALLS (design §5). Rooted at
    // gfx/engine (the fixed diamond) + each backend module (a no-op for sokol
    // android, whose modules do not import core — but design-faithful and
    // resilient). Replaces the enum `android_deps` unrolled overrides +
    // `unifyGfxSubpackageCore`. The `unifyCoreDiamond` def itself is emitted as a
    // top-level helper after the build fn (see `emitCoreDiamondWalk`).
    try w.writeAll(
        \\
        \\    // Generic core+gfx-diamond unification (design §5) — the loop form of
        \\    // the per-site overrideImport diamond (golden cell, not the desktop
        \\    // byte-anchor's unrolled form). Rooted at each imported provider.
        \\    var core_diamond_visited: std.AutoHashMapUnmanaged(*std.Build.Module, void) = .empty;
        \\    unifyCoreDiamond(b.allocator, gfx_mod, core_mod, gfx_mod, &core_diamond_visited);
        \\    unifyCoreDiamond(b.allocator, engine_mod, core_mod, gfx_mod, &core_diamond_visited);
        \\
    );
    for (m.modules) |mod| {
        const alias = try moduleAlias(allocator, mod);
        defer allocator.free(alias);
        try w.print("    unifyCoreDiamond(b.allocator, {s}, core_mod, gfx_mod, &core_diamond_visited);\n", .{alias});
    }
}

/// v2 android LINK — the DECLARATIVE link graph (design §2: **D**): link each
/// platform artifact, `link_libc`, and each `.system_libs.android` entry — plus
/// the `post_wire` hook CALL for the residual (**H-post**): NDK sysroot include
/// paths, `addLibraryPath(usr/lib/<triple>/<api>)`, and libc.txt. The android root
/// artifact is `lib` (a dynamic library), not `exe`.
fn renderAndroidLinkV2(m: BackendManifestV2, cfg: ProjectConfig, w: anytype) !void {
    const android = m.platforms.android orelse return error.V2PlatformUnsupported;

    // GENERATED (D): link the platform artifact(s) into the .so.
    for (android.artifacts) |art| {
        try w.print("    lib.root_module.linkLibrary({s});\n", .{art.name});
    }
    // GENERATED (D): libc for the NDK build.
    if (android.link_libc) try w.writeAll("    lib.root_module.link_libc = true;\n");
    // GENERATED (D): the Android NDK system libs (`.system_libs.android`).
    for (m.system_libs.android) |lib_name| {
        try w.print("    lib.root_module.linkSystemLibrary(\"{s}\", .{{}});\n", .{lib_name});
    }

    // GENERATED (H-post): the residual the manifest cannot express statically —
    // NDK sysroot include/lib paths + libc.txt — delegated to the backend hook's
    // `post_wire` (design §4). `android_target_sdk` is REQUIRED (never a silent 34
    // default): it comes from `cfg.android.target_sdk_version`, which always has a
    // concrete value, and the hook PANICS on null.
    const android_sdk: u32 = if (cfg.android) |a| a.target_sdk_version else 34;
    try w.print(
        \\
        \\    // post_wire (design §4) — NDK sysroot include/lib paths + libc.txt.
        \\    backend_build_hook.post_wire(b, .{{
        \\        .manifest_version = {d},
        \\        .backend_dep = backend_dep,
        \\        .root_module = lib.root_module,
        \\        .root_artifact = lib,
        \\        .target = android_target,
        \\        .optimize = optimize,
        \\        .platform = .android,
        \\        .ios_sdk_path = null,
        \\        .android_target_sdk = {d},
        \\    }});
        \\
    , .{ manifest_v2.HOOK_ABI_VERSION, android_sdk });
}

// ──────────────────────────────────────────────────────────────────────────
// IOS v2 emitters (PR 6, golden cell). iOS is the second HOOK-BEARING conversion
// (design §8). Its `resolve_target` is DISTINCT from android's: besides the
// `ResolvedTarget` it also runs `xcrun` SDK discovery and returns the SDK PATH,
// because plugin `b.dependency` calls consume it (`build_files.zig:341`) and it
// therefore must be resolved BEFORE any dependency (design §4 review-correction
// #6). `post_wire` then consumes that SDK path (residual (b): `configureSdkPaths`
// / `addExeSdkPaths`); the iOS frameworks + `link_libc` are DECLARATIVE
// (`.frameworks.ios`), emitted here. Like android this is a GOLDEN cell (§7): the
// residual moved into the hook and the unrolled core-diamond overrides became the
// generic `unifyCoreDiamond` loop, so the text legitimately DIFFERS from the enum
// `header_ios`/`ios_deps`/`backend_sokol_ios`/`ios_link` path.
// ──────────────────────────────────────────────────────────────────────────

/// v2 ios HEADER — replaces the enum `header_ios` block. Instead of inlining
/// `getIosSdkPath`/`configureSdkPaths`/`addExeSdkPaths`/`linkIosFrameworks` + the
/// device/simulator target block, it imports the backend hook and resolves BOTH
/// the ios target AND the SDK path via `resolve_target` (design §4, runs BEFORE
/// any `b.dependency`). `sdk_path` is captured at the build-fn top because the
/// plugin dep loop threads it into each plugin `b.dependency` call, and the
/// `post_wire` context consumes it for the SDK include/lib/framework paths.
pub fn renderIosHeaderV2(m: BackendManifestV2, w: anytype) !void {
    _ = m.platforms.ios orelse return error.V2PlatformUnsupported;
    try w.print(
        \\const std = @import("std");
        \\
        \\const backend_build_hook = @import("{s}");
        \\
        \\pub fn build(b: *std.Build) void {{
        \\    const optimize = b.standardOptimizeOption(.{{}});
        \\
        \\    // resolve_target (design §4) — the backend hook runs xcrun SDK discovery
        \\    // + device/simulator selection, producing BOTH the ios target and the
        \\    // SDK path plugin b.dependency calls consume, BEFORE any b.dependency.
        \\    const ios_resolved = backend_build_hook.resolve_target(b, .{{ .platform = .ios }});
        \\    const ios_target = ios_resolved.target;
        \\    const sdk_path = ios_resolved.ios_sdk_path.?;
        \\
        \\
    , .{hook_import_name});
}

/// v2 ios core/gfx/engine dep decls — the declarative half of the enum `ios_deps`
/// section, WITHOUT the unrolled `overrideImport` diamond + `unifyGfxSubpackageCore`
/// (those are replaced by the generic `unifyCoreDiamond` walk emitted after the
/// backend-dep section, design §5).
pub fn renderIosDepsDeclsV2(w: anytype) !void {
    try w.writeAll(
        \\    const core_dep = b.dependency("labelle_core", .{ .target = ios_target, .optimize = optimize });
        \\    const core_mod = core_dep.module("labelle-core");
        \\
        \\    const gfx_dep = b.dependency("labelle_gfx", .{ .target = ios_target, .optimize = optimize });
        \\    const gfx_mod = gfx_dep.module("labelle-gfx");
        \\
        \\    const engine_dep = b.dependency("engine", .{ .target = ios_target, .optimize = optimize });
        \\    const engine_mod = engine_dep.module("engine");
        \\
        \\
    );
}

/// v2 ios backend-dep — the generic `b.dependency` literal (`.target = ios_target`)
/// + `.module(...)` decls (honoring `root_alias`) + `.artifact` decls. Then the
/// generic core-diamond walk CALLS (design §5) rooted at gfx/engine + each backend
/// module — replacing the enum `ios_deps` unrolled overrides. The SDK-path
/// `configureSdkPaths(sokol_clib, sdk_path)` the enum path calls here is NOT
/// emitted; it is `post_wire`'s job (emitted in the link section).
fn renderIosBackendDepV2(
    allocator: std.mem.Allocator,
    m: BackendManifestV2,
    cfg: ProjectConfig,
    w: anytype,
) !void {
    const ios = m.platforms.ios orelse return error.V2PlatformUnsupported;

    // GENERATED: `const backend_dep = b.dependency("<dep_name>", .{ .target =
    // ios_target, .optimize = optimize, <merged dep_options> });`
    const opts = try mergeDepOptions(allocator, m.dep_options, ios.dep_options);
    defer allocator.free(opts);
    try w.print("    const backend_dep = b.dependency(\"{s}\", .{{ .target = ios_target, .optimize = optimize", .{m.dep_name});
    for (opts) |opt| {
        try w.print(", .{s} = {s}", .{ opt.name, depOptionValue(opt.value, cfg) });
    }
    try w.writeAll(" });\n");

    // GENERATED: provider module decls under their root alias.
    for (m.modules) |mod| {
        const alias = try moduleAlias(allocator, mod);
        defer allocator.free(alias);
        try w.print("    const {s} = backend_dep.module(\"{s}\");\n", .{ alias, mod.name });
    }

    // GENERATED: artifact decls + declarative `.pic` (ios has none; design §2 note 1).
    for (ios.artifacts) |art| {
        try w.print("    const {s} = backend_dep.artifact(\"{s}\");\n", .{ art.name, art.name });
        if (art.pic) try w.print("    {s}.root_module.pic = true;\n", .{art.name});
    }

    // GENERATED: the generic core+gfx-diamond walk CALLS (design §5) — the loop
    // form of the per-site overrideImport diamond, replacing the enum `ios_deps`
    // unrolled overrides + `unifyGfxSubpackageCore`. The `unifyCoreDiamond` def is
    // emitted as a top-level helper after the build fn (see `emitCoreDiamondWalk`).
    try w.writeAll(
        \\
        \\    // Generic core+gfx-diamond unification (design §5) — the loop form of
        \\    // the per-site overrideImport diamond (golden cell, not the desktop
        \\    // byte-anchor's unrolled form). Rooted at each imported provider.
        \\    var core_diamond_visited: std.AutoHashMapUnmanaged(*std.Build.Module, void) = .empty;
        \\    unifyCoreDiamond(b.allocator, gfx_mod, core_mod, gfx_mod, &core_diamond_visited);
        \\    unifyCoreDiamond(b.allocator, engine_mod, core_mod, gfx_mod, &core_diamond_visited);
        \\
    );
    for (m.modules) |mod| {
        const alias = try moduleAlias(allocator, mod);
        defer allocator.free(alias);
        try w.print("    unifyCoreDiamond(b.allocator, {s}, core_mod, gfx_mod, &core_diamond_visited);\n", .{alias});
    }
}

/// v2 ios LINK — the DECLARATIVE link graph (design §2: **D**): link each platform
/// artifact, `link_libc`, and each `.frameworks.ios` entry → `linkFramework` — plus
/// the `post_wire` hook CALL for the residual (**H-post**): the SDK include/lib/
/// framework paths (`configureSdkPaths`/`addExeSdkPaths`) that consume the SDK path
/// resolved in `resolve_target`. The ios root artifact is `exe` (an executable).
fn renderIosLinkV2(m: BackendManifestV2, w: anytype) !void {
    const ios = m.platforms.ios orelse return error.V2PlatformUnsupported;

    // GENERATED (D): link the platform artifact(s) into the exe.
    for (ios.artifacts) |art| {
        try w.print("    exe.root_module.linkLibrary({s});\n", .{art.name});
    }
    // GENERATED (D): libc for the ios build (`ios_link:582`).
    if (ios.link_libc) try w.writeAll("    exe.root_module.link_libc = true;\n");
    // GENERATED (D): the ios system frameworks (`.frameworks.ios`) — replaces the
    // enum `linkIosFrameworks` helper call.
    for (m.frameworks.ios) |fw| {
        try w.print("    exe.root_module.linkFramework(\"{s}\", .{{}});\n", .{fw});
    }

    // GENERATED (H-post): the residual the manifest cannot express statically —
    // the SDK include/lib/framework paths — delegated to the backend hook's
    // `post_wire` (design §4). `ios_sdk_path` is REQUIRED (resolved in
    // `resolve_target`); `android_target_sdk` is null on ios.
    try w.print(
        \\
        \\    // post_wire (design §4) — iOS SDK include/lib/framework paths.
        \\    backend_build_hook.post_wire(b, .{{
        \\        .manifest_version = {d},
        \\        .backend_dep = backend_dep,
        \\        .root_module = exe.root_module,
        \\        .root_artifact = exe,
        \\        .target = ios_target,
        \\        .optimize = optimize,
        \\        .platform = .ios,
        \\        .ios_sdk_path = sdk_path,
        \\        .android_target_sdk = null,
        \\    }});
        \\
    , .{manifest_v2.HOOK_ABI_VERSION});
}

/// v2 replacement for the link enum branch (`writeSection(.., "link_<tag>")`) / the
/// v1 `renderLinkSection`. Dispatches on the target platform: DESKTOP (PR 3 byte
/// anchor) and ANDROID (PR 5 golden cell).
pub fn renderLinkSectionV2(
    allocator: std.mem.Allocator,
    m: BackendManifestV2,
    cfg: ProjectConfig,
    w: anytype,
) !void {
    switch (cfg.platform) {
        .desktop => try renderDesktopLinkV2(m, w),
        .android => try renderAndroidLinkV2(m, cfg, w),
        .ios => try renderIosLinkV2(m, w),
        else => return error.V2PlatformUnsupported,
    }
    _ = allocator;
}

/// DESKTOP link (PR 3 byte anchor). Generated from the manifest: the
/// `linkLibrary(<artifact>)` line(s). The per-OS framework switch + its prose is
/// anchor residual (its `.macos, .ios =>` combined arm + libudev NOTE are
/// idiosyncratic formatting, not declarative graph data).
fn renderDesktopLinkV2(m: BackendManifestV2, w: anytype) !void {
    const desktop = m.platforms.desktop orelse return error.V2PlatformUnsupported;

    // GENERATED: link each platform artifact.
    for (desktop.artifacts) |art| {
        try w.print("    exe.root_module.linkLibrary({s});\n", .{art.name});
    }

    // Anchor residual: the framework switch (from `.frameworks.desktop`) + prose.
    try w.writeAll(anchor_link_body);
}

/// Look up the `PlatformEntry` for a `config.Platform` on a v2 manifest. Absent
/// platform = unsupported by this backend.
pub fn platformEntry(
    m: BackendManifestV2,
    platform: config.Platform,
) ?BackendManifestV2.PlatformEntry {
    return switch (platform) {
        .desktop => m.platforms.desktop,
        .android => m.platforms.android,
        .ios => m.platforms.ios,
        .wasm => m.platforms.wasm,
    };
}

/// v2 packaging seam (design §3/§6): delegate a platform's packaging to the
/// shared packager, driven by the typed `PlatformEntry.package` recipe. The v2
/// codegen has no `switch (cfg.platform)` — it drives packaging off manifest
/// data — so this is the single entry point every v2 platform path calls.
///
/// Desktop's `.binary` recipe is a NO-OP, so this is safe to call
/// unconditionally on the PR-3 desktop path without disturbing its byte anchor.
/// Android/wasm entries (PRs 5/7) carry `.apk`/`.web` recipes that emit the
/// apk-staging / emcc packaging block here, byte-identical to the enum path's
/// `.android_package` / `.wasm_footer` sections (design §7).
pub fn renderPackageV2(
    m: BackendManifestV2,
    platform: config.Platform,
    w: anytype,
) !void {
    const entry = platformEntry(m, platform) orelse return error.V2PlatformUnsupported;
    try packager.emitPackage(entry.package, w);
}

// ──────────────────────────────────────────────────────────────────────────
// sokol-desktop byte-anchor VERBATIM RESIDUAL (§7).
//
// The non-declarative text the v2 model does not carry, reproduced byte-exactly
// from `backends/sokol/build_fragments/{backend_dep,link}.txt` so the desktop
// anchor hits 0-diff against the enum/v1 path. This is the desktop "unroll" of the
// core-diamond walk + the backend-specific prose; it is deleted with the enum
// path + v1 fragments in PR 12, at which point the desktop cell becomes a golden
// snapshot like every other. See the module doc for why the generic walk is NOT
// spliced on this path.
// ──────────────────────────────────────────────────────────────────────────

const anchor_head_comment =
    "    // `with_imgui` flips sokol_imgui.c compilation on. MUST match the\n    // imgui bridge's option set when the project includes imgui, or\n    // Zig caches two `sokol_clib` artifacts (and two `_sg` states) —\n    // see comment in `backends/sokol/build.zig` (labelle-assembler#140).";

const anchor_tail_overrides =
    "\n    // Unify the app core onto the transitive `sdl_gamepad` desktop gamepad\n    // source — same diamond as `.backend_raylib` (see the note there). The\n    // sokol `input` module reaches `GamepadEvent` through `sdl_gamepad`\n    // (imported under the `labelle_core` underscore key) rather than a direct\n    // core import, so the override target is the sdl_gamepad module, not\n    // `input`. `if` guard: only desktop sokol wires sdl_gamepad in (Android/iOS\n    // use their own gamepad paths; wasm has none). See labelle-assembler#271.\n    if (backend_input.import_table.get(\"sdl_gamepad\")) |sdl_gp_mod| {\n        overrideImport(sdl_gp_mod, \"labelle_core\", core_mod);\n    }\n\n    // Linux desktop core gamepad route (core#33 scope 2): there the sokol\n    // backend wires a DIRECT `labelle-core` import on `input` (reaching the\n    // udev/evdev gamepad source) instead of `sdl_gamepad`. Unify the app\n    // core onto it so gamepad state/event types match the engine's. `if`\n    // guard: the import only exists on Linux desktop builds — adding the\n    // override unconditionally would inject a dead import elsewhere (#258).\n    if (backend_input.import_table.get(\"labelle-core\")) |_| {\n        overrideImport(backend_input, \"labelle-core\", core_mod);\n    }\n\n";

const anchor_link_body =
    "\n    // IOSurface + CoreFoundation are needed for the macOS preview-mode\n    // IOSurface producer (labelle-assembler#121 + #125, labelle-\n    // engine#547). The engine references `IOSurfaceCreate`,\n    // `IOSurfaceLock`, `CFNumberCreate`, etc. via `@extern \"c\"` —\n    // these symbols live in IOSurface.framework + CoreFoundation\n    // .framework, and sokol's upstream linker line does not propagate\n    // them. Same on iOS (the framework path is identical). Linux /\n    // Windows / web have no macOS-specific symbols to resolve here,\n    // so the framework links are gated on the Darwin target tags.\n    switch (target.result.os.tag) {\n        .macos, .ios => {\n            exe.root_module.linkFramework(\"IOSurface\", .{});\n            exe.root_module.linkFramework(\"CoreFoundation\", .{});\n        },\n        // NOTE: labelle-core's Linux gamepad-detection source\n        // (gamepad_source/linux.zig, labelle-assembler#249) does NOT need a\n        // build-time libudev link. As of labelle-core#20 it loads libudev at\n        // RUNTIME via std.DynLib (dlopen of `libudev.so.1`) and degrades\n        // gracefully when the library is absent — so the generated build must\n        // not link `-ludev`, which would reintroduce a hard build/runtime\n        // dependency. Runtime device-access setup (input group / udev\n        // `uaccess` rule, Flatpak `--device=input`) is in docs/gamepad-linux.md.\n        else => {},\n    }\n\n";

// ============================================================================
// Tests
// ============================================================================

const testing = std.testing;

test "mergeDepOptions: base first, then per-platform appends (sokol desktop order)" {
    const base = [_]DepOption{.{ .name = "with_imgui", .value = .gui_is_imgui }};
    const per = [_]DepOption{
        .{ .name = "gamepad_enabled", .value = .gamepad_enabled },
        .{ .name = "gamepad_hidapi", .value = .gamepad_hidapi },
    };
    const merged = try mergeDepOptions(testing.allocator, &base, &per);
    defer testing.allocator.free(merged);
    try testing.expectEqual(@as(usize, 3), merged.len);
    try testing.expectEqualStrings("with_imgui", merged[0].name);
    try testing.expectEqualStrings("gamepad_enabled", merged[1].name);
    try testing.expectEqualStrings("gamepad_hidapi", merged[2].name);
}

test "mergeDepOptions: per-platform overrides a base entry by name, no duplicate" {
    const base = [_]DepOption{.{ .name = "with_imgui", .value = .gui_is_imgui }};
    const per = [_]DepOption{.{ .name = "with_imgui", .value = .true_literal }};
    const merged = try mergeDepOptions(testing.allocator, &base, &per);
    defer testing.allocator.free(merged);
    try testing.expectEqual(@as(usize, 1), merged.len);
    try testing.expectEqual(DepOption.ValueSource.true_literal, merged[0].value);
}

test "depOptionValue: closed predicate set matches the v1 paramValue predicates" {
    const base_cfg = ProjectConfig{ .name = "g" };
    // gamepad defaults to .auto → gamepad_enabled true; hidapi false; no gui → false.
    try testing.expectEqualStrings("true", depOptionValue(.gamepad_enabled, base_cfg));
    try testing.expectEqualStrings("false", depOptionValue(.gamepad_hidapi, base_cfg));
    try testing.expectEqualStrings("false", depOptionValue(.gui_is_imgui, base_cfg));
    try testing.expectEqualStrings("true", depOptionValue(.true_literal, base_cfg));
    try testing.expectEqualStrings("false", depOptionValue(.false_literal, base_cfg));
}

test "moduleAlias: default is backend_<name>, explicit alias preserved" {
    const a = try moduleAlias(testing.allocator, .{ .name = "gfx", .source = "x" });
    defer testing.allocator.free(a);
    try testing.expectEqualStrings("backend_gfx", a);

    const b = try moduleAlias(testing.allocator, .{ .name = "android_app", .root_alias = "backend_app", .source = "x" });
    defer testing.allocator.free(b);
    try testing.expectEqualStrings("backend_app", b);
}

test "emitCoreDiamondWalk emits the PR-2 generic walk source (drift guard)" {
    var buf: std.ArrayList(u8) = .empty;
    defer buf.deinit(testing.allocator);
    var aw: std.Io.Writer.Allocating = .init(testing.allocator);
    defer aw.deinit();
    try emitCoreDiamondWalk(&aw.writer);
    const out = aw.written();
    try testing.expect(std.mem.indexOf(u8, out, "fn unifyCoreDiamond(") != null);
    try testing.expect(std.mem.indexOf(u8, out, "labelle-gfx") != null);
}

// A minimal v2 manifest exercising all four platform packaging recipes: desktop
// `.binary` (no-op), android `.apk`, wasm `.web`; ios absent (unsupported).
fn packagingManifest() BackendManifestV2 {
    const entry = struct {
        fn e(pkg: BackendManifestV2.Package) BackendManifestV2.PlatformEntry {
            return .{ .entry = "t.txt", .loop_style = .callback, .target = .native, .package = pkg };
        }
    }.e;
    return .{
        .manifest_version = 2,
        .dir_name = "sokol",
        .dep_name = "labelle_sokol",
        .modules = &.{},
        .platforms = .{
            .desktop = entry(.binary),
            .android = entry(.{ .apk = .{ .manifest = "AndroidManifest.xml.tmpl" } }),
            .wasm = entry(.{ .web = .{ .shell = null } }),
        },
    };
}

fn renderPackageToOwned(m: BackendManifestV2, platform: config.Platform) ![]u8 {
    var aw: std.Io.Writer.Allocating = .init(testing.allocator);
    errdefer aw.deinit();
    try renderPackageV2(m, platform, &aw.writer);
    return aw.toOwnedSlice();
}

test "renderPackageV2: desktop .binary is a no-op (preserves the byte anchor)" {
    const out = try renderPackageToOwned(packagingManifest(), .desktop);
    defer testing.allocator.free(out);
    try testing.expectEqual(@as(usize, 0), out.len);
}

test "renderPackageV2: android delegates to the packager apk recipe" {
    const out = try renderPackageToOwned(packagingManifest(), .android);
    defer testing.allocator.free(out);
    try testing.expectEqualStrings(packager.apk_package_zig, out);
}

test "renderPackageV2: wasm delegates to the packager web recipe" {
    const out = try renderPackageToOwned(packagingManifest(), .wasm);
    defer testing.allocator.free(out);
    try testing.expectEqualStrings(packager.web_package_zig, out);
}

test "renderPackageV2: an absent platform is unsupported" {
    var aw: std.Io.Writer.Allocating = .init(testing.allocator);
    defer aw.deinit();
    try testing.expectError(
        error.V2PlatformUnsupported,
        renderPackageV2(packagingManifest(), .ios, &aw.writer),
    );
}
