//! Manifest **v2** desktop codegen splice (epic #453 item 3, PR 3 — see
//! `docs/design/manifest-v2-build-graph.md` §3/§5/§7). This is the codegen half
//! of manifest-v2: it renders a project's backend-dep + link wiring from a typed,
//! declarative `BackendManifestV2` (PR 1) instead of the v1 raw-text fragments.
//!
//! Gated in `build_files.zig` on `manifest_version >= 2` (via
//! `manifest_v2.parseManifest`): a v1 (or field-less) manifest keeps the existing
//! `manifest_splice` + enum path byte-unchanged; only a v2 manifest reaches here.
//! PR 3 wires only the DESKTOP platform entry (the byte anchor); other platforms
//! land in PRs 5/6/7 with the hook phases + shared packager.
//!
//! ## The desktop byte anchor (§7) — why this reproduces the exact enum/v1 text
//!
//! §7 makes the sokol-desktop cell the ONE hard enum-vs-v2 0-diff anchor: "the v2
//! path can be emitted so it reproduces that exact text (unrolling the walk's
//! output for the desktop case)". So the DECLARATIVE lines the v2 model owns —
//! the `b.dependency` literal (dep name + the base↔per-platform `dep_options`
//! merge, each value from the closed `ValueSource` predicate set), the provider
//! `.module(...)` decls (honoring `root_alias`), the `.artifact(...)` decls, and
//! the `linkLibrary`/framework wiring — are GENERATED here from the manifest, and
//! this generated output is what proves the v2 data reproduces the baseline
//! option/module/artifact set byte-for-byte.
//!
//! The NON-declarative residual the v2 model deliberately does NOT carry — the
//! backend-specific prose comments (#140/#271/#258/#121) and the two hand-written
//! core-diamond `overrideImport` `if`-blocks (classified **CORE** in §2, destined
//! for the generic `core_diamond.unifyCoreDiamond` walk) — is emitted as
//! VERBATIM anchor residual (`anchor_head_comment`/`anchor_tail_overrides`/
//! `anchor_link_body`, generated byte-exactly from the retained fixture
//! fragments). This is precisely §7's "unrolling the walk's output for the desktop
//! case": the desktop cell keeps the unrolled override statements (not the generic
//! walk call) so the anchor hits 0-diff. Splicing the generic
//! `core_diamond.generated_walk_zig` here INSTEAD would change the generated text
//! (a walk call + helper def ≠ the unrolled `if`-blocks) and break the 0-diff
//! anchor — so it is intentionally NOT spliced on the desktop path. The generic
//! walk stays validated by PR 2's tests + `emitCoreDiamondWalk` (a drift
//! guard) and is the mechanism the golden-snapshot cells (PR 5+) use, where the
//! gate is a reviewed golden — not byte-identity — exactly because a loop emits
//! different source than the unrolled form (§7 tier-1).
//!
//! When the enum path is deleted (§6 step 5 / PR 12) the anchor's baseline is
//! gone, the desktop cell becomes a golden snapshot too, and this verbatim
//! residual is deleted with the v1 fragments it mirrors.
//!
//! ── Barrel ──────────────────────────────────────────────────────────
//! This file was a single ~1500-line module; it is now a thin barrel that
//! re-exports the public surface from focused per-platform sub-modules under
//! `manifest_v2_splice/` (behavior-preserving split, mirrors #539). Every symbol
//! keeps its original name and identity so existing `manifest_v2_splice.<Name>`
//! call sites are unchanged:
//!
//!   - `manifest_v2_splice/common.zig`   — cross-platform helpers (dep-option
//!                                          values, merge, module/artifact idents,
//!                                          the generic walk splice, byte-anchor
//!                                          discriminator, hook staging, packaging,
//!                                          root build-deps).
//!   - `manifest_v2_splice/desktop.zig`  — desktop byte-anchor + generic emitters
//!                                          and the sokol anchor residual.
//!   - `manifest_v2_splice/android.zig`  — android header/deps/backend-dep/link.
//!   - `manifest_v2_splice/ios.zig`      — ios header/deps/backend-dep/link.
//!   - `manifest_v2_splice/wasm.zig`     — wasm header/deps/backend-dep/link/footer.
//!   - `manifest_v2_splice/dispatch.zig` — the backend-dep + link section routers.

const common = @import("manifest_v2_splice/common.zig");
const desktop = @import("manifest_v2_splice/desktop.zig");
const android = @import("manifest_v2_splice/android.zig");
const ios = @import("manifest_v2_splice/ios.zig");
const wasm = @import("manifest_v2_splice/wasm.zig");
const dispatch = @import("manifest_v2_splice/dispatch.zig");

// ── Cross-platform helpers (manifest_v2_splice/common.zig) ───────────
pub const emitCoreDiamondWalk = common.emitCoreDiamondWalk;
pub const isDesktopByteAnchor = common.isDesktopByteAnchor;
pub const hook_import_name = common.hook_import_name;
pub const stageBackendBuildHook = common.stageBackendBuildHook;
pub const platformEntry = common.platformEntry;
pub const renderPackageV2 = common.renderPackageV2;
pub const emitRootBuildDepsV2 = common.emitRootBuildDepsV2;

// ── Section dispatchers (manifest_v2_splice/dispatch.zig) ────────────
pub const renderBackendDepSectionV2 = dispatch.renderBackendDepSectionV2;
pub const renderLinkSectionV2 = dispatch.renderLinkSectionV2;

// ── Desktop emitters (manifest_v2_splice/desktop.zig) ────────────────
pub const renderDesktopDepsDeclsV2 = desktop.renderDesktopDepsDeclsV2;
pub const renderDesktopTestLinkGenericV2 = desktop.renderDesktopTestLinkGenericV2;

// ── Android emitters (manifest_v2_splice/android.zig) ────────────────
pub const renderAndroidHeaderV2 = android.renderAndroidHeaderV2;
pub const renderAndroidDepsDeclsV2 = android.renderAndroidDepsDeclsV2;

// ── iOS emitters (manifest_v2_splice/ios.zig) ────────────────────────
pub const renderIosHeaderV2 = ios.renderIosHeaderV2;
pub const renderIosDepsDeclsV2 = ios.renderIosDepsDeclsV2;

// ── WASM emitters (manifest_v2_splice/wasm.zig) ──────────────────────
pub const renderWasmHeaderV2 = wasm.renderWasmHeaderV2;
pub const renderWasmDepsDeclsV2 = wasm.renderWasmDepsDeclsV2;
pub const renderWasmFooterV2 = wasm.renderWasmFooterV2;

// Pull every sub-module's tests into the `manifest_v2_splice.zig` analysis so
// `zig build test` keeps running the specs that used to live here.
test {
    _ = common;
    _ = desktop;
    _ = android;
    _ = ios;
    _ = wasm;
    _ = dispatch;
}
