//! Manifest **v2** desktop codegen splice (epic #453 item 3, PR 3 — see
//! `docs/design/manifest-v2-build-graph.md` §3/§5/§7). This is the codegen half
//! of manifest-v2: it renders a project's backend-dep + link wiring from a typed,
//! declarative `BackendManifestV2` (PR 1) instead of the v1 raw-text fragments.
//!
//! Gated in `build_files.zig` on `manifest_version >= 2` (via
//! `manifest_v2.parseManifest`): a v1 (or field-less) manifest keeps the existing
//! `manifest_splice` + enum path byte-unchanged; only a v2 manifest reaches here.
//! PR 3 wires only the DESKTOP platform entry (the byte anchor); other platforms
//! land in PRs 5/6/7 with the hook phases + shared packager.
//!
//! ## The desktop byte anchor (§7) — why this reproduces the exact enum/v1 text
//!
//! §7 makes the sokol-desktop cell the ONE hard enum-vs-v2 0-diff anchor: "the v2
//! path can be emitted so it reproduces that exact text (unrolling the walk's
//! output for the desktop case)". So the DECLARATIVE lines the v2 model owns —
//! the `b.dependency` literal (dep name + the base↔per-platform `dep_options`
//! merge, each value from the closed `ValueSource` predicate set), the provider
//! `.module(...)` decls (honoring `root_alias`), the `.artifact(...)` decls, and
//! the `linkLibrary`/framework wiring — are GENERATED here from the manifest, and
//! this generated output is what proves the v2 data reproduces the baseline
//! option/module/artifact set byte-for-byte.
//!
//! The NON-declarative residual the v2 model deliberately does NOT carry — the
//! backend-specific prose comments (#140/#271/#258/#121) and the two hand-written
//! core-diamond `overrideImport` `if`-blocks (classified **CORE** in §2, destined
//! for the generic `core_diamond.unifyCoreDiamond` walk) — is emitted here as
//! VERBATIM anchor residual (`anchor_head_comment`/`anchor_tail_overrides`/
//! `anchor_link_body`, generated byte-exactly from the retained fixture
//! fragments). This is precisely §7's "unrolling the walk's output for the desktop
//! case": the desktop cell keeps the unrolled override statements (not the generic
//! walk call) so the anchor hits 0-diff. Splicing the generic
//! `core_diamond.generated_walk_zig` here INSTEAD would change the generated text
//! (a walk call + helper def ≠ the unrolled `if`-blocks) and break the 0-diff
//! anchor — so it is intentionally NOT spliced on the desktop path. The generic
//! walk stays validated by PR 2's tests + `emitCoreDiamondWalk` below (a drift
//! guard) and is the mechanism the golden-snapshot cells (PR 5+) use, where the
//! gate is a reviewed golden — not byte-identity — exactly because a loop emits
//! different source than the unrolled form (§7 tier-1).
//!
//! When the enum path is deleted (§6 step 5 / PR 12) the anchor's baseline is
//! gone, the desktop cell becomes a golden snapshot too, and this verbatim
//! residual is deleted with the v1 fragments it mirrors.

const std = @import("std");
const config = @import("../config.zig");
const manifest_v2 = @import("manifest_v2.zig");
const core_diamond = @import("core_diamond.zig");

const BackendManifestV2 = manifest_v2.BackendManifestV2;
const DepOption = BackendManifestV2.DepOption;
const ProjectConfig = config.ProjectConfig;

// ── Closed dependency-option value predicate set (design §4) ──────────────
// Names are declarative manifest data; VALUES come from this closed predicate
// set the assembler computes — the EXACT `paramValue` predicates the v1 splice
// uses today (`manifest_splice.zig:272`-`289`), plus the literal true/false the
// mobile `dont_link_system_libs` flag needs. The result is the literal `"true"`/
// `"false"` rendered into the generated `b.dependency` options struct.
fn depOptionValue(vs: DepOption.ValueSource, cfg: ProjectConfig) []const u8 {
    return switch (vs) {
        // with_imgui / gui_enabled: true iff the resolved gui plugin is imgui.
        .gui_is_imgui => if (cfg.resolved_gui) |gui|
            (if (std.mem.eql(u8, gui.name, "imgui")) "true" else "false")
        else
            "false",
        .gamepad_enabled => if (cfg.gamepad == .auto) "true" else "false",
        .gamepad_hidapi => if (cfg.gamepad_hidapi) "true" else "false",
        .true_literal => "true",
        .false_literal => "false",
    };
}

/// The base↔per-platform `dep_options` merge (design §3/§4 merge contract): start
/// from the base list, then for each per-platform entry OVERRIDE a base entry of
/// the same `name` (per-platform value wins) or APPEND it. No subtractive form.
/// Returns an allocator-owned slice the caller frees. Order is base entries first
/// (in declaration order), then per-platform appends — matching the enum-path
/// `b.dependency` literal order.
fn mergeDepOptions(
    allocator: std.mem.Allocator,
    base: []const DepOption,
    per_platform: []const DepOption,
) ![]DepOption {
    var out: std.ArrayList(DepOption) = .empty;
    errdefer out.deinit(allocator);
    for (base) |b| try out.append(allocator, b);
    for (per_platform) |p| {
        var overridden = false;
        for (out.items) |*existing| {
            if (std.mem.eql(u8, existing.name, p.name)) {
                existing.value = p.value; // override-by-name
                overridden = true;
                break;
            }
        }
        if (!overridden) try out.append(allocator, p); // append
    }
    return out.toOwnedSlice(allocator);
}

/// Root import alias for a provider module: `root_alias` if declared, else the
/// default `backend_<name>` (design §3 `ModuleDecl.root_alias`). Caller owns the
/// returned slice.
fn moduleAlias(allocator: std.mem.Allocator, mod: BackendManifestV2.ModuleDecl) ![]const u8 {
    if (mod.root_alias) |a| return allocator.dupe(u8, a);
    return std.fmt.allocPrint(allocator, "backend_{s}", .{mod.name});
}

/// Emit the generic core+gfx-diamond walk helper (`core_diamond.generated_walk_zig`)
/// into the generated build.zig. NOT used on the desktop byte-anchor path (which
/// unrolls — see the module doc); this is the spliceable mechanism for the
/// golden-snapshot cells (PR 5+) and a compile/drift guard that keeps this module
/// referencing the PR-2 walk source.
pub fn emitCoreDiamondWalk(w: anytype) !void {
    try w.writeAll(core_diamond.generated_walk_zig);
}

/// v2 replacement for the backend-dep enum branch (`renderSection(.., "backend_<tag>")`)
/// / the v1 `renderBackendDepSection`. DESKTOP only in PR 3.
///
/// Generated from the manifest: the `b.dependency` literal (dep name + merged
/// `dep_options`), the `.module(...)` decls (honoring `root_alias`), and the
/// `.artifact(...)` decls. The surrounding prose + unrolled core-diamond overrides
/// are the anchor residual (see module doc).
pub fn renderBackendDepSectionV2(
    allocator: std.mem.Allocator,
    m: BackendManifestV2,
    cfg: ProjectConfig,
    w: anytype,
) !void {
    const desktop = m.platforms.desktop orelse return error.V2PlatformUnsupported;

    // HEAD: backend-specific provenance prose (not declarative). Anchor residual.
    try w.writeAll(anchor_head_comment);
    try w.writeByte('\n');

    // GENERATED: `const backend_dep = b.dependency("<dep_name>", .{ .target =
    // target, .optimize = optimize, <merged dep_options> });`
    const opts = try mergeDepOptions(allocator, m.dep_options, desktop.dep_options);
    defer allocator.free(opts);
    try w.print("    const backend_dep = b.dependency(\"{s}\", .{{ .target = target, .optimize = optimize", .{m.dep_name});
    for (opts) |opt| {
        try w.print(", .{s} = {s}", .{ opt.name, depOptionValue(opt.value, cfg) });
    }
    try w.writeAll(" });\n");

    // GENERATED: provider module decls under their root alias.
    for (m.modules) |mod| {
        const alias = try moduleAlias(allocator, mod);
        defer allocator.free(alias);
        try w.print("    const {s} = backend_dep.module(\"{s}\");\n", .{ alias, mod.name });
    }

    // GENERATED: artifact decls for this platform (the var name IS the artifact
    // name, matching the enum path: `const sokol_clib = backend_dep.artifact(...)`).
    for (desktop.artifacts) |art| {
        try w.print("    const {s} = backend_dep.artifact(\"{s}\");\n", .{ art.name, art.name });
    }

    // TAIL: the two unrolled core-diamond `overrideImport` `if`-blocks + prose.
    // Anchor residual — §7 "unrolling the walk's output for the desktop case".
    try w.writeAll(anchor_tail_overrides);
}

/// v2 replacement for the link enum branch (`writeSection(.., "link_<tag>")`) / the
/// v1 `renderLinkSection`. DESKTOP only in PR 3.
///
/// Generated from the manifest: the `linkLibrary(<artifact>)` line(s). The per-OS
/// framework switch + its prose is anchor residual (its `.macos, .ios =>` combined
/// arm + libudev NOTE are idiosyncratic formatting, not declarative graph data).
pub fn renderLinkSectionV2(
    _: std.mem.Allocator,
    m: BackendManifestV2,
    _: ProjectConfig,
    w: anytype,
) !void {
    const desktop = m.platforms.desktop orelse return error.V2PlatformUnsupported;

    // GENERATED: link each platform artifact.
    for (desktop.artifacts) |art| {
        try w.print("    exe.root_module.linkLibrary({s});\n", .{art.name});
    }

    // Anchor residual: the framework switch (from `.frameworks.desktop`) + prose.
    try w.writeAll(anchor_link_body);
}

// ──────────────────────────────────────────────────────────────────────────
// sokol-desktop byte-anchor VERBATIM RESIDUAL (§7).
//
// The non-declarative text the v2 model does not carry, reproduced byte-exactly
// from `backends/sokol/build_fragments/{backend_dep,link}.txt` so the desktop
// anchor hits 0-diff against the enum/v1 path. This is the desktop "unroll" of the
// core-diamond walk + the backend-specific prose; it is deleted with the enum
// path + v1 fragments in PR 12, at which point the desktop cell becomes a golden
// snapshot like every other. See the module doc for why the generic walk is NOT
// spliced on this path.
// ──────────────────────────────────────────────────────────────────────────

const anchor_head_comment =
    "    // `with_imgui` flips sokol_imgui.c compilation on. MUST match the\n    // imgui bridge's option set when the project includes imgui, or\n    // Zig caches two `sokol_clib` artifacts (and two `_sg` states) —\n    // see comment in `backends/sokol/build.zig` (labelle-assembler#140).";

const anchor_tail_overrides =
    "\n    // Unify the app core onto the transitive `sdl_gamepad` desktop gamepad\n    // source — same diamond as `.backend_raylib` (see the note there). The\n    // sokol `input` module reaches `GamepadEvent` through `sdl_gamepad`\n    // (imported under the `labelle_core` underscore key) rather than a direct\n    // core import, so the override target is the sdl_gamepad module, not\n    // `input`. `if` guard: only desktop sokol wires sdl_gamepad in (Android/iOS\n    // use their own gamepad paths; wasm has none). See labelle-assembler#271.\n    if (backend_input.import_table.get(\"sdl_gamepad\")) |sdl_gp_mod| {\n        overrideImport(sdl_gp_mod, \"labelle_core\", core_mod);\n    }\n\n    // Linux desktop core gamepad route (core#33 scope 2): there the sokol\n    // backend wires a DIRECT `labelle-core` import on `input` (reaching the\n    // udev/evdev gamepad source) instead of `sdl_gamepad`. Unify the app\n    // core onto it so gamepad state/event types match the engine's. `if`\n    // guard: the import only exists on Linux desktop builds — adding the\n    // override unconditionally would inject a dead import elsewhere (#258).\n    if (backend_input.import_table.get(\"labelle-core\")) |_| {\n        overrideImport(backend_input, \"labelle-core\", core_mod);\n    }\n\n";

const anchor_link_body =
    "\n    // IOSurface + CoreFoundation are needed for the macOS preview-mode\n    // IOSurface producer (labelle-assembler#121 + #125, labelle-\n    // engine#547). The engine references `IOSurfaceCreate`,\n    // `IOSurfaceLock`, `CFNumberCreate`, etc. via `@extern \"c\"` —\n    // these symbols live in IOSurface.framework + CoreFoundation\n    // .framework, and sokol's upstream linker line does not propagate\n    // them. Same on iOS (the framework path is identical). Linux /\n    // Windows / web have no macOS-specific symbols to resolve here,\n    // so the framework links are gated on the Darwin target tags.\n    switch (target.result.os.tag) {\n        .macos, .ios => {\n            exe.root_module.linkFramework(\"IOSurface\", .{});\n            exe.root_module.linkFramework(\"CoreFoundation\", .{});\n        },\n        // NOTE: labelle-core's Linux gamepad-detection source\n        // (gamepad_source/linux.zig, labelle-assembler#249) does NOT need a\n        // build-time libudev link. As of labelle-core#20 it loads libudev at\n        // RUNTIME via std.DynLib (dlopen of `libudev.so.1`) and degrades\n        // gracefully when the library is absent — so the generated build must\n        // not link `-ludev`, which would reintroduce a hard build/runtime\n        // dependency. Runtime device-access setup (input group / udev\n        // `uaccess` rule, Flatpak `--device=input`) is in docs/gamepad-linux.md.\n        else => {},\n    }\n\n";

// ============================================================================
// Tests
// ============================================================================

const testing = std.testing;

test "mergeDepOptions: base first, then per-platform appends (sokol desktop order)" {
    const base = [_]DepOption{.{ .name = "with_imgui", .value = .gui_is_imgui }};
    const per = [_]DepOption{
        .{ .name = "gamepad_enabled", .value = .gamepad_enabled },
        .{ .name = "gamepad_hidapi", .value = .gamepad_hidapi },
    };
    const merged = try mergeDepOptions(testing.allocator, &base, &per);
    defer testing.allocator.free(merged);
    try testing.expectEqual(@as(usize, 3), merged.len);
    try testing.expectEqualStrings("with_imgui", merged[0].name);
    try testing.expectEqualStrings("gamepad_enabled", merged[1].name);
    try testing.expectEqualStrings("gamepad_hidapi", merged[2].name);
}

test "mergeDepOptions: per-platform overrides a base entry by name, no duplicate" {
    const base = [_]DepOption{.{ .name = "with_imgui", .value = .gui_is_imgui }};
    const per = [_]DepOption{.{ .name = "with_imgui", .value = .true_literal }};
    const merged = try mergeDepOptions(testing.allocator, &base, &per);
    defer testing.allocator.free(merged);
    try testing.expectEqual(@as(usize, 1), merged.len);
    try testing.expectEqual(DepOption.ValueSource.true_literal, merged[0].value);
}

test "depOptionValue: closed predicate set matches the v1 paramValue predicates" {
    const base_cfg = ProjectConfig{ .name = "g" };
    // gamepad defaults to .auto → gamepad_enabled true; hidapi false; no gui → false.
    try testing.expectEqualStrings("true", depOptionValue(.gamepad_enabled, base_cfg));
    try testing.expectEqualStrings("false", depOptionValue(.gamepad_hidapi, base_cfg));
    try testing.expectEqualStrings("false", depOptionValue(.gui_is_imgui, base_cfg));
    try testing.expectEqualStrings("true", depOptionValue(.true_literal, base_cfg));
    try testing.expectEqualStrings("false", depOptionValue(.false_literal, base_cfg));
}

test "moduleAlias: default is backend_<name>, explicit alias preserved" {
    const a = try moduleAlias(testing.allocator, .{ .name = "gfx", .source = "x" });
    defer testing.allocator.free(a);
    try testing.expectEqualStrings("backend_gfx", a);

    const b = try moduleAlias(testing.allocator, .{ .name = "android_app", .root_alias = "backend_app", .source = "x" });
    defer testing.allocator.free(b);
    try testing.expectEqualStrings("backend_app", b);
}

test "emitCoreDiamondWalk emits the PR-2 generic walk source (drift guard)" {
    var buf: std.ArrayList(u8) = .empty;
    defer buf.deinit(testing.allocator);
    var aw: std.Io.Writer.Allocating = .init(testing.allocator);
    defer aw.deinit();
    try emitCoreDiamondWalk(&aw.writer);
    const out = aw.written();
    try testing.expect(std.mem.indexOf(u8, out, "fn unifyCoreDiamond(") != null);
    try testing.expect(std.mem.indexOf(u8, out, "labelle-gfx") != null);
}
