//! Per-pack module root generation — `__pack_root.zig` (assembler#498
//! PR 2, "wire the wall").
//!
//! A light pack's files used to be path-imported straight from the
//! generated `main.zig`, which put every pack `.zig` in the ROOT module
//! with its full import table — `game`, every sibling pack (via
//! relative paths), the whole tree. The only "these files may only
//! import X, Y, Z" mechanism Zig has is the module boundary, so each
//! pack becomes a real build-system module rooted at a generated
//! `<target>/packs/<name>/__pack_root.zig` (naming mirrors
//! `__tests_root.zig`) that re-exports every scanned file. The
//! generated `main.zig` then reaches pack contents EXCLUSIVELY through
//! `@import("pack__<prefix>")` — path-importing a pack file from the
//! root module after this would be the "file exists in modules 'root'
//! and 'pack__<prefix>'" compile error (the same dual-membership error
//! the FlowNodes script promotion documents in `registries.zig`).
//!
//! What the module's import table deliberately EXCLUDES is the wall:
//! no `game` shim, no sibling packs. It INCLUDES the shared substrate —
//! engine/core/gfx, the backend modules, and every decl-module plugin —
//! because plugins are the sanctioned inter-domain surface (FP's packs
//! route worker access through `worker_controller`'s citizens surface,
//! per the pack's own boundary docs), plus the implicit `contracts`
//! pack when the project declares one (`pack_validate.IMPLICIT_DEPS`).
//! `depends_on` surface modules land in PR 4; the `@import("root")`
//! Registry bridge + `@import("pack")` self-import land in PR 3.
//!
//! Prefab `.jsonc` files stay `@embedFile`d by path from `main.zig` —
//! data files have no module membership, and the embed path + the
//! `<pack>__<name>` registration key are the save contract.

const std = @import("std");
const scan = @import("scan.zig");

/// The build-graph identity of one pack module, threaded from
/// `generate()`'s `pack_scans` into `BuildZigOptions` so the generated
/// build.zig declares `pack__<prefix>_mod` and the target artifacts
/// `addImport` it. `prefix` is `scan.packNamespacePrefix(name)` — the
/// same sanitized ident every other `<pack>__` symbol uses.
pub const PackModule = struct {
    /// Manifest/plugin name, verbatim (directory name under `packs/`).
    name: []const u8,
    /// Sanitized `<pack>__` ident prefix (owned by the caller).
    prefix: []const u8,
};

/// The implicit shared-contracts pack name (`pack_validate.IMPLICIT_DEPS`):
/// when a project declares a pack with this name, every OTHER pack module
/// gets it wired as `@import("contracts")`.
pub const CONTRACTS_PACK_NAME = "contracts";

/// `packs/<name>/scripts/<rel>` → `<rel>`. Pack script entries carry a
/// full target-relative `rel_path` (labelle-assembler#487); inside the
/// pack MODULE the same file is `scripts/<rel>` relative to
/// `__pack_root.zig`. Falls back to the input when the shape is
/// unexpected (defensive — the scanner only ever produces the
/// `packs/<name>/scripts/` form for pack entries).
pub fn packRelScriptPath(rel_path: []const u8, pack_name: []const u8) []const u8 {
    var buf: [512]u8 = undefined;
    const prefix = std.fmt.bufPrint(&buf, "packs/{s}/scripts/", .{pack_name}) catch return rel_path;
    if (std.mem.startsWith(u8, rel_path, prefix)) return rel_path[prefix.len..];
    return rel_path;
}

/// Render the pack's `__pack_root.zig` source. `script_rels` are the
/// pack's script paths RELATIVE TO the pack's `scripts/` dir (see
/// `packRelScriptPath`); components/events/hooks come from the
/// `PackScan` stems. Every decl name is `scan.pathToIdent` of the
/// stem/rel-path — the exact accessor the main.zig emission sites
/// print after `@import("pack__<prefix>").<section>.`, so the two
/// sides can never drift.
///
/// Sections are emitted only when non-empty; a pack with only prefabs
/// produces a module with nothing but the header (still a valid module
/// root — the build graph wires it unconditionally so the wiring shape
/// doesn't depend on which convention dirs a pack happens to use).
pub fn renderPackRoot(
    allocator: std.mem.Allocator,
    pack: scan.PackScan,
    script_rels: []const []const u8,
) ![]const u8 {
    var alloc_writer: std.Io.Writer.Allocating = .init(allocator);
    errdefer alloc_writer.deinit();
    const w = &alloc_writer.writer;

    try w.print(
        \\//! Generated by labelle-assembler — DO NOT EDIT.
        \\//! Module root of pack '{s}' (assembler#498 "wire the wall").
        \\//!
        \\//! Everything the generated main.zig consumes from this pack is
        \\//! re-exported here; the pack's files belong to THIS module, so a
        \\//! path-import of any of them from another module is a compile
        \\//! error — that boundary is the pack isolation contract.
        \\
        \\
    , .{pack.name});

    var ident_buf: [256]u8 = undefined;

    if (pack.component_names.len > 0) {
        try w.writeAll("pub const components = struct {\n");
        for (pack.component_names) |stem| {
            const ident = scan.pathToIdent(stem, &ident_buf);
            try w.print("    pub const {s} = @import(\"components/{s}.zig\");\n", .{ ident, stem });
        }
        try w.writeAll("};\n\n");
    }

    if (pack.event_names.len > 0) {
        try w.writeAll("pub const events = struct {\n");
        for (pack.event_names) |stem| {
            const ident = scan.pathToIdent(stem, &ident_buf);
            try w.print("    pub const {s} = @import(\"events/{s}.zig\");\n", .{ ident, stem });
        }
        try w.writeAll("};\n\n");
    }

    if (pack.hook_names.len > 0) {
        try w.writeAll("pub const hooks = struct {\n");
        for (pack.hook_names) |stem| {
            const ident = scan.pathToIdent(stem, &ident_buf);
            try w.print("    pub const {s} = @import(\"hooks/{s}.zig\");\n", .{ ident, stem });
        }
        try w.writeAll("};\n\n");
    }

    if (script_rels.len > 0) {
        try w.writeAll("pub const scripts = struct {\n");
        for (script_rels) |rel| {
            const ident = scan.pathToIdent(rel, &ident_buf);
            try w.print("    pub const {s} = @import(\"scripts/{s}\");\n", .{ ident, rel });
        }
        try w.writeAll("};\n");
    }

    var arr_list = alloc_writer.toArrayList();
    // `toArrayList` resets the writer, so its errdefer no longer covers
    // the buffer — without this, an OOM inside `toOwnedSlice` leaks it
    // (no double-free: the reset writer's deinit is a no-op).
    errdefer arr_list.deinit(allocator);
    return arr_list.toOwnedSlice(allocator);
}
