//! Game constants, phase 1 (RFC-CONSTANTS in labelle-engine#811 / #810).
//!
//! Scans `constants/*.yaml` in the game dir, parses each through the strict
//! subset (`constants_yaml.zig`), and emits `constants.zig` into the target
//! dir: one nested namespace per file, every value a `pub const` carrying the
//! literal exactly as written. `5.0` stays comptime_float and `5` stays
//! comptime_int, which is the distinction the RFC's scalar-kind rule needs.
//!
//! The invariant every assembler feature holds: a project with no `constants/`
//! directory emits nothing and keeps a byte-identical build.zig. A previously
//! generated `constants.zig` is deleted when the directory goes away, so a
//! stale module cannot shadow the feature being turned off.
//!
//! Phase 2 lives here too: after a successful emit, the game's .zig sources
//! are scanned (usage_scan.zig -- conservative alias widening, warnings only)
//! and every constant nothing reads is named with its yaml file and line.
//! Phase 3 (pack constants, game-over-pack precedence) is deliberately
//! absent; see the phasing table in RFC-CONSTANTS.
const std = @import("std");
const Allocator = std.mem.Allocator;
const yaml = @import("constants_yaml.zig");
const usage = @import("usage_scan.zig");

// Not config.globalIo(): config.zig pulls in build_options, which would make
// this file untestable standalone (`zig test src/constants_phase.zig`) for the
// sake of one accessor. Same mechanism, locally owned, lazily initialised.
var _threaded: std.Io.Threaded = undefined;
var _io: std.Io = undefined;
var _io_ready = false;

fn phaseIo() std.Io {
    if (!_io_ready) {
        _threaded = std.Io.Threaded.init(std.heap.page_allocator, .{});
        _io = _threaded.io();
        _io_ready = true;
    }
    return _io;
}

pub const GENERATED_FILENAME = "constants.zig";

/// Runs the phase. Returns true when a `constants.zig` was emitted (the build
/// wiring keys off this), false when the game has no `constants/` directory.
///
/// Validation failures print `file:line: message` to stderr and return
/// `error.ConstantsInvalid`, matching the tone of the other phases: the value
/// someone mistyped is named, not summarised.
pub fn runPhase(
    allocator: Allocator,
    game_dir: []const u8,
    target_dir: []const u8,
) !bool {
    const io = phaseIo();
    const cwd = std.Io.Dir.cwd();

    var arena_state = std.heap.ArenaAllocator.init(allocator);
    defer arena_state.deinit();
    const arena = arena_state.allocator();

    const src_path = try std.fs.path.join(arena, &.{ game_dir, "constants" });

    var src_dir = cwd.openDir(io, src_path, .{ .iterate = true }) catch |err| switch (err) {
        error.FileNotFound, error.NotDir => {
            // No constants/ -- remove any stale generated file and emit nothing.
            const stale = try std.fs.path.join(arena, &.{ target_dir, GENERATED_FILENAME });
            cwd.deleteFile(io, stale) catch {};
            return false;
        },
        else => return err,
    };
    defer src_dir.close(io);

    // Collect *.yaml, sorted, so the generated file is deterministic under
    // directory-iteration order differences between filesystems.
    var names: std.ArrayList([]const u8) = .empty;
    var iter = src_dir.iterate();
    while (iter.next(io) catch null) |entry| {
        if (entry.kind != .file) continue;
        if (!std.mem.endsWith(u8, entry.name, ".yaml")) continue;
        try names.append(arena, try arena.dupe(u8, entry.name));
    }
    std.mem.sort([]const u8, names.items, {}, struct {
        fn lessThan(_: void, a: []const u8, b: []const u8) bool {
            return std.mem.order(u8, a, b) == .lt;
        }
    }.lessThan);

    if (names.items.len == 0) {
        const stale = try std.fs.path.join(arena, &.{ target_dir, GENERATED_FILENAME });
        cwd.deleteFile(io, stale) catch {};
        return false;
    }

    var leaves: std.ArrayList(Leaf) = .empty;
    var out: std.Io.Writer.Allocating = .init(arena);
    const w = &out.writer;
    try w.writeAll(
        \\//! Generated by labelle-assembler from constants/*.yaml — do not edit.
        \\//! Values are emitted verbatim, so 5.0 is comptime_float and 5 is
        \\//! comptime_int; they coerce at the use site (RFC-CONSTANTS §3).
        \\
        \\pub const C = struct {
        \\
    );

    var had_error = false;
    for (names.items) |name| {
        const stem = name[0 .. name.len - ".yaml".len];
        if (!isIdentifier(stem)) {
            std.debug.print("constants/{s}: filename must be a Zig identifier (it becomes the C.{s} namespace)\n", .{ name, stem });
            had_error = true;
            continue;
        }

        const source = src_dir.readFileAlloc(io, name, arena, .limited(1024 * 1024)) catch |err| switch (err) {
            error.StreamTooLong => {
                std.debug.print("constants/{s}: file exceeds 1 MiB, which no constants file should\n", .{name});
                had_error = true;
                continue;
            },
            else => return err,
        };

        switch (try yaml.parse(arena, source)) {
            .fail => |e| {
                std.debug.print("constants/{s}:{d}: {s}\n", .{ name, e.line, e.msg });
                had_error = true;
            },
            .root => |root| {
                try w.print("    pub const {s} = struct {{\n", .{stem});
                try emitMapping(w, &root, 2);
                try w.writeAll("    };\n");
                try collectLeaves(arena, &leaves, name, stem, &root);
            },
        }
    }
    try w.writeAll("};\n");

    if (had_error) return error.ConstantsInvalid;

    const dst = try std.fs.path.join(arena, &.{ target_dir, GENERATED_FILENAME });
    try cwd.writeFile(io, .{ .sub_path = dst, .data = out.writer.buffered() });

    // Phase 2: usage warnings. Never fails the build -- a warning that can be
    // wrong teaches people to ignore it, so the scan errs toward "used" and
    // this errs toward silence on any I/O trouble.
    warnUnused(arena, game_dir, leaves.items) catch {};
    return true;
}

/// One emitted constant: where it can be addressed from code, and where it
/// was written, so the warning points at the yaml rather than at nothing.
const Leaf = struct {
    /// Root-relative dotted path, domain first: "decay.hunger.rate".
    path: []const u8,
    file: []const u8,
    line: usize,
};

fn collectLeaves(
    arena: Allocator,
    leaves: *std.ArrayList(Leaf),
    file: []const u8,
    prefix: []const u8,
    m: *const yaml.Mapping,
) Allocator.Error!void {
    for (m.entries.items) |e| {
        const path = try std.fmt.allocPrint(arena, "{s}.{s}", .{ prefix, e.key });
        switch (e.node) {
            .mapping => |child| try collectLeaves(arena, leaves, file, path, child),
            .scalar => |sc| try leaves.append(arena, .{ .path = path, .file = file, .line = sc.line }),
        }
    }
}

/// Scans every .zig file under the game dir (skipping generated and vendored
/// trees) and prints one warning per constant nothing reads.
fn warnUnused(arena: Allocator, game_dir: []const u8, leaves: []const Leaf) !void {
    var marks = usage.Marks.init(arena);
    try collectMarks(arena, &marks, game_dir);

    for (leaves) |leaf| {
        if (!marks.covers(leaf.path)) {
            std.debug.print("warning: constants/{s}:{d}: C.{s} is never read\n", .{ leaf.file, leaf.line, leaf.path });
        }
    }
}

/// Skipped wholesale: generated output, vendored deps, caches, VCS.
const skip_dirs = [_][]const u8{ ".labelle", ".git", "deps", "zig-out", "zig-cache", ".zig-cache" };

fn collectMarks(arena: Allocator, marks: *usage.Marks, dir_path: []const u8) !void {
    const io = phaseIo();
    const cwd = std.Io.Dir.cwd();
    var dir = cwd.openDir(io, dir_path, .{ .iterate = true }) catch return;
    defer dir.close(io);

    var iter = dir.iterate();
    while (iter.next(io) catch null) |entry| {
        switch (entry.kind) {
            .directory => {
                var skip = false;
                for (skip_dirs) |d| {
                    if (std.mem.eql(u8, entry.name, d)) skip = true;
                }
                if (skip) continue;
                const sub = try std.fs.path.join(arena, &.{ dir_path, entry.name });
                try collectMarks(arena, marks, sub);
            },
            .file => {
                if (!std.mem.endsWith(u8, entry.name, ".zig")) continue;
                const source = dir.readFileAlloc(io, entry.name, arena, .limited(4 * 1024 * 1024)) catch continue;
                try usage.scanSource(marks, .{}, source);
            },
            else => {},
        }
    }
}

fn emitMapping(w: *std.Io.Writer, m: *const yaml.Mapping, depth: usize) std.Io.Writer.Error!void {
    for (m.entries.items) |e| {
        try writeIndent(w, depth);
        switch (e.node) {
            .mapping => |child| {
                try w.print("pub const {s} = struct {{\n", .{e.key});
                try emitMapping(w, child, depth + 1);
                try writeIndent(w, depth);
                try w.writeAll("};\n");
            },
            .scalar => |sc| switch (sc.kind) {
                // Verbatim: the emitted literal is the YAML text, which is
                // what keeps int/float distinct and `1.20` printing as 1.20.
                .int, .float, .bool => try w.print("pub const {s} = {s};\n", .{ e.key, sc.text }),
                .string => {
                    try w.print("pub const {s} = \"", .{e.key});
                    try writeEscaped(w, sc.text);
                    try w.writeAll("\";\n");
                },
            },
        }
    }
}

fn writeIndent(w: *std.Io.Writer, depth: usize) std.Io.Writer.Error!void {
    var i: usize = 0;
    while (i < depth) : (i += 1) try w.writeAll("    ");
}

fn writeEscaped(w: *std.Io.Writer, s: []const u8) std.Io.Writer.Error!void {
    for (s) |c| switch (c) {
        '\\' => try w.writeAll("\\\\"),
        '"' => try w.writeAll("\\\""),
        '\n' => try w.writeAll("\\n"),
        '\t' => try w.writeAll("\\t"),
        '\r' => try w.writeAll("\\r"),
        else => try w.writeByte(c),
    };
}

fn isIdentifier(s: []const u8) bool {
    if (s.len == 0) return false;
    if (!std.ascii.isAlphabetic(s[0]) and s[0] != '_') return false;
    for (s[1..]) |c| {
        if (!std.ascii.isAlphanumeric(c) and c != '_') return false;
    }
    return true;
}

// ---------------------------------------------------------------------------
// tests
// ---------------------------------------------------------------------------

const testing = std.testing;

test "runPhase: no constants dir emits nothing and cleans a stale file" {
    const io = phaseIo();
    var tmp = std.testing.tmpDir(.{});
    defer tmp.cleanup();

    try tmp.dir.createDirPath(io, "game");
    try tmp.dir.createDirPath(io, "target");
    // A stale file from a previous run with constants/ present.
    try tmp.dir.writeFile(io, .{ .sub_path = "target/" ++ GENERATED_FILENAME, .data = "// stale\n" });

    var rel_buf: [96]u8 = undefined;
    const rel = try std.fmt.bufPrint(&rel_buf, ".zig-cache/tmp/{s}", .{&tmp.sub_path});
    const game = try std.fs.path.join(testing.allocator, &.{ rel, "game" });
    defer testing.allocator.free(game);
    const target = try std.fs.path.join(testing.allocator, &.{ rel, "target" });
    defer testing.allocator.free(target);

    try testing.expectEqual(false, try runPhase(testing.allocator, game, target));
    // The stale file is gone.
    try testing.expectError(error.FileNotFound, tmp.dir.openFile(io, "target/" ++ GENERATED_FILENAME, .{}));
}

test "runPhase: files become namespaces, values stay verbatim, order is by filename" {
    const io = phaseIo();
    var tmp = std.testing.tmpDir(.{});
    defer tmp.cleanup();

    try tmp.dir.createDirPath(io, "game/constants");
    try tmp.dir.createDirPath(io, "target");
    try tmp.dir.writeFile(io, .{ .sub_path = "game/constants/decay.yaml", .data =
        \\hunger:
        \\  rate: 0.02
        \\health:
        \\  drain_rate: 0.0   # DISABLED
        \\
    });
    try tmp.dir.writeFile(io, .{ .sub_path = "game/constants/construction.yaml", .data =
        \\build_time: 5.0
        \\max_workers: 4
        \\site_label: "em obras"
        \\enabled: true
        \\
    });
    // Not .yaml: ignored, not an error.
    try tmp.dir.writeFile(io, .{ .sub_path = "game/constants/notes.txt", .data = "irrelevant" });

    var rel_buf: [96]u8 = undefined;
    const rel = try std.fmt.bufPrint(&rel_buf, ".zig-cache/tmp/{s}", .{&tmp.sub_path});
    const game = try std.fs.path.join(testing.allocator, &.{ rel, "game" });
    defer testing.allocator.free(game);
    const target = try std.fs.path.join(testing.allocator, &.{ rel, "target" });
    defer testing.allocator.free(target);

    try testing.expectEqual(true, try runPhase(testing.allocator, game, target));

    const generated = try tmp.dir.readFileAlloc(io, "target/" ++ GENERATED_FILENAME, testing.allocator, .limited(64 * 1024));
    defer testing.allocator.free(generated);

    // construction sorts before decay, so namespaces come in that order.
    const c_at = std.mem.indexOf(u8, generated, "pub const construction = struct {").?;
    const d_at = std.mem.indexOf(u8, generated, "pub const decay = struct {").?;
    try testing.expect(c_at < d_at);

    try testing.expect(std.mem.indexOf(u8, generated, "pub const build_time = 5.0;") != null);
    try testing.expect(std.mem.indexOf(u8, generated, "pub const max_workers = 4;") != null);
    try testing.expect(std.mem.indexOf(u8, generated, "pub const site_label = \"em obras\";") != null);
    try testing.expect(std.mem.indexOf(u8, generated, "pub const enabled = true;") != null);
    try testing.expect(std.mem.indexOf(u8, generated, "pub const drain_rate = 0.0;") != null);

    // And the generated file is real Zig with the values reachable: compile it.
    // (The ast-check is cheap and catches emitter breakage structurally.)
    const source_z = try testing.allocator.dupeZ(u8, generated);
    defer testing.allocator.free(source_z);
    var ast = try std.zig.Ast.parse(testing.allocator, source_z, .zig);
    defer ast.deinit(testing.allocator);
    try testing.expectEqual(@as(usize, 0), ast.errors.len);
}

test "runPhase: a bad value names the file and line and fails the phase" {
    const io = phaseIo();
    var tmp = std.testing.tmpDir(.{});
    defer tmp.cleanup();

    try tmp.dir.createDirPath(io, "game/constants");
    try tmp.dir.createDirPath(io, "target");
    try tmp.dir.writeFile(io, .{ .sub_path = "game/constants/flags.yaml", .data = "enabled: no\n" });

    var rel_buf: [96]u8 = undefined;
    const rel = try std.fmt.bufPrint(&rel_buf, ".zig-cache/tmp/{s}", .{&tmp.sub_path});
    const game = try std.fs.path.join(testing.allocator, &.{ rel, "game" });
    defer testing.allocator.free(game);
    const target = try std.fs.path.join(testing.allocator, &.{ rel, "target" });
    defer testing.allocator.free(target);

    try testing.expectError(error.ConstantsInvalid, runPhase(testing.allocator, game, target));
    // Nothing half-written.
    try testing.expectError(error.FileNotFound, tmp.dir.openFile(io, "target/" ++ GENERATED_FILENAME, .{}));
}

test "runPhase: a non-identifier filename is rejected" {
    const io = phaseIo();
    var tmp = std.testing.tmpDir(.{});
    defer tmp.cleanup();

    try tmp.dir.createDirPath(io, "game/constants");
    try tmp.dir.createDirPath(io, "target");
    try tmp.dir.writeFile(io, .{ .sub_path = "game/constants/ship-speeds.yaml", .data = "a: 1\n" });

    var rel_buf: [96]u8 = undefined;
    const rel = try std.fmt.bufPrint(&rel_buf, ".zig-cache/tmp/{s}", .{&tmp.sub_path});
    const game = try std.fs.path.join(testing.allocator, &.{ rel, "game" });
    defer testing.allocator.free(game);
    const target = try std.fs.path.join(testing.allocator, &.{ rel, "target" });
    defer testing.allocator.free(target);

    try testing.expectError(error.ConstantsInvalid, runPhase(testing.allocator, game, target));
}

test "collectMarks walks the game tree and skips generated dirs" {
    const io = phaseIo();
    var tmp = std.testing.tmpDir(.{});
    defer tmp.cleanup();

    try tmp.dir.createDirPath(io, "game/scripts/playing");
    try tmp.dir.createDirPath(io, "game/libs/needs");
    try tmp.dir.createDirPath(io, "game/.labelle/target");
    try tmp.dir.writeFile(io, .{
        .sub_path = "game/scripts/playing/10_decay.zig",
        .data = "const C = @import(\"constants\").C;\nconst cfg = C.decay.hunger;\npub fn tick() f32 { return cfg.rate; }\n",
    });
    try tmp.dir.writeFile(io, .{
        .sub_path = "game/libs/needs/config.zig",
        .data = "const C = @import(\"constants\").C;\npub const t = C.construction.build_time;\n",
    });
    // A use inside generated output must NOT count -- it is our own emission.
    try tmp.dir.writeFile(io, .{
        .sub_path = "game/.labelle/target/main.zig",
        .data = "const C = @import(\"constants\").C;\npub const x = C.construction.max_workers;\n",
    });

    var rel_buf: [96]u8 = undefined;
    const rel = try std.fmt.bufPrint(&rel_buf, ".zig-cache/tmp/{s}", .{&tmp.sub_path});
    const game = try std.fs.path.join(testing.allocator, &.{ rel, "game" });
    defer testing.allocator.free(game);

    var arena_state = std.heap.ArenaAllocator.init(testing.allocator);
    defer arena_state.deinit();
    var marks = usage.Marks.init(arena_state.allocator());
    try collectMarks(arena_state.allocator(), &marks, game);

    try testing.expect(marks.covers("decay.hunger.rate")); // via the alias subtree
    try testing.expect(marks.covers("construction.build_time")); // direct, from libs/
    try testing.expect(!marks.covers("construction.max_workers")); // only in .labelle
    try testing.expect(!marks.covers("decay.health.drain_rate"));
}
