/// Generated by labelle-cli — do not edit.
const std = @import("std");
const engine = @import("labelle-engine");
const BackendGfx = @import("backend_gfx");
const BackendInput = @import("backend_input");
const BackendAudio = @import("backend_audio");
const window = @import("backend_window");
// Log sink (default: stderr). Override in project template to disable or customize.
const LogSink = engine.core.StderrLogSink;
const EcsBackend = engine.MockEcsBackend(u32);
const GuiBackend = engine.StubGui;

// --- External backend contract verification (labelle-assembler#386 Phase 6b) ---
// Assert the fetched out-of-tree backend satisfies labelle-core's render /
// window / input contracts, naming any missing decl HERE rather than deep in
// engine wiring. Built-in backends skip this (vetted by the enum path).
comptime {
    const _backend_contract_core = @import("labelle-core");

    // --- Directional per-sub-surface contract-VERSION asserts (labelle-assembler#453) ---
    // Emitted BEFORE the shape asserts below: a `targets_<surface>_contract`
    // mismatch must report the DIRECTIONAL "upgrade labelle-core / upgrade the
    // backend" message FIRST -- if a shape assert @compileError'd first (a
    // decl the newer contract renamed/added), that directional guidance would
    // never fire. Each surface is checked only when the backend opts in by
    // declaring `targets_<surface>_contract` (@hasDecl guard = no flag day).
    const _bc_gfx = @import("backend_gfx");
    const _bc_window = @import("backend_window");
    const _bc_input = @import("backend_input");
    const _bc_audio = @import("backend_audio");
    if (@hasDecl(_bc_gfx, "targets_draw_contract")) {
        if (_bc_gfx.targets_draw_contract > _backend_contract_core.DRAW_CONTRACT_VERSION)
            @compileError(std.fmt.comptimePrint("backend targets draw-contract v{d} but this labelle-core provides v{d} -- upgrade labelle-core", .{ _bc_gfx.targets_draw_contract, _backend_contract_core.DRAW_CONTRACT_VERSION }));
        if (_bc_gfx.targets_draw_contract < _backend_contract_core.DRAW_CONTRACT_VERSION)
            @compileError(std.fmt.comptimePrint("backend targets draw-contract v{d} but this labelle-core expects v{d} -- a breaking draw-contract change landed; upgrade the backend", .{ _bc_gfx.targets_draw_contract, _backend_contract_core.DRAW_CONTRACT_VERSION }));
    }
    if (@hasDecl(_bc_gfx, "targets_loader_contract")) {
        if (_bc_gfx.targets_loader_contract > _backend_contract_core.LOADER_CONTRACT_VERSION)
            @compileError(std.fmt.comptimePrint("backend targets loader-contract v{d} but this labelle-core provides v{d} -- upgrade labelle-core", .{ _bc_gfx.targets_loader_contract, _backend_contract_core.LOADER_CONTRACT_VERSION }));
        if (_bc_gfx.targets_loader_contract < _backend_contract_core.LOADER_CONTRACT_VERSION)
            @compileError(std.fmt.comptimePrint("backend targets loader-contract v{d} but this labelle-core expects v{d} -- a breaking loader-contract change landed; upgrade the backend", .{ _bc_gfx.targets_loader_contract, _backend_contract_core.LOADER_CONTRACT_VERSION }));
    }
    if (@hasDecl(_bc_window, "targets_window_contract")) {
        if (_bc_window.targets_window_contract > _backend_contract_core.WINDOW_CONTRACT_VERSION)
            @compileError(std.fmt.comptimePrint("backend targets window-contract v{d} but this labelle-core provides v{d} -- upgrade labelle-core", .{ _bc_window.targets_window_contract, _backend_contract_core.WINDOW_CONTRACT_VERSION }));
        if (_bc_window.targets_window_contract < _backend_contract_core.WINDOW_CONTRACT_VERSION)
            @compileError(std.fmt.comptimePrint("backend targets window-contract v{d} but this labelle-core expects v{d} -- a breaking window-contract change landed; upgrade the backend", .{ _bc_window.targets_window_contract, _backend_contract_core.WINDOW_CONTRACT_VERSION }));
    }
    if (@hasDecl(_bc_input, "targets_input_contract")) {
        if (_bc_input.targets_input_contract > _backend_contract_core.INPUT_CONTRACT_VERSION)
            @compileError(std.fmt.comptimePrint("backend targets input-contract v{d} but this labelle-core provides v{d} -- upgrade labelle-core", .{ _bc_input.targets_input_contract, _backend_contract_core.INPUT_CONTRACT_VERSION }));
        if (_bc_input.targets_input_contract < _backend_contract_core.INPUT_CONTRACT_VERSION)
            @compileError(std.fmt.comptimePrint("backend targets input-contract v{d} but this labelle-core expects v{d} -- a breaking input-contract change landed; upgrade the backend", .{ _bc_input.targets_input_contract, _backend_contract_core.INPUT_CONTRACT_VERSION }));
    }
    if (@hasDecl(_bc_audio, "targets_audio_playback_contract")) {
        if (_bc_audio.targets_audio_playback_contract > _backend_contract_core.AUDIO_PLAYBACK_CONTRACT_VERSION)
            @compileError(std.fmt.comptimePrint("backend targets audio-playback-contract v{d} but this labelle-core provides v{d} -- upgrade labelle-core", .{ _bc_audio.targets_audio_playback_contract, _backend_contract_core.AUDIO_PLAYBACK_CONTRACT_VERSION }));
        if (_bc_audio.targets_audio_playback_contract < _backend_contract_core.AUDIO_PLAYBACK_CONTRACT_VERSION)
            @compileError(std.fmt.comptimePrint("backend targets audio-playback-contract v{d} but this labelle-core expects v{d} -- a breaking audio-playback-contract change landed; upgrade the backend", .{ _bc_audio.targets_audio_playback_contract, _backend_contract_core.AUDIO_PLAYBACK_CONTRACT_VERSION }));
    }
    if (@hasDecl(_bc_audio, "targets_audio_loader_contract")) {
        if (_bc_audio.targets_audio_loader_contract > _backend_contract_core.AUDIO_LOADER_CONTRACT_VERSION)
            @compileError(std.fmt.comptimePrint("backend targets audio-loader-contract v{d} but this labelle-core provides v{d} -- upgrade labelle-core", .{ _bc_audio.targets_audio_loader_contract, _backend_contract_core.AUDIO_LOADER_CONTRACT_VERSION }));
        if (_bc_audio.targets_audio_loader_contract < _backend_contract_core.AUDIO_LOADER_CONTRACT_VERSION)
            @compileError(std.fmt.comptimePrint("backend targets audio-loader-contract v{d} but this labelle-core expects v{d} -- a breaking audio-loader-contract change landed; upgrade the backend", .{ _bc_audio.targets_audio_loader_contract, _backend_contract_core.AUDIO_LOADER_CONTRACT_VERSION }));
    }

    // Shape asserts run AFTER the version asserts above (see note there):
    // the backend must satisfy labelle-core's render / window / input contract
    // SURFACE (every required decl present) once its version is known-compatible.
    _backend_contract_core.assertBackend(@import("backend_gfx"));
    _backend_contract_core.assertWindow(@import("backend_window"));
    _backend_contract_core.assertInput(@import("backend_input"));
}

const gfx = @import("labelle-gfx");

const GameLayers = enum(u8) {
    background,
    world,
    ui,

    pub fn config(self: GameLayers) gfx.LayerConfig {
        return switch (self) {
            .background => .{ .order = 0, .space = .screen },
            .world => .{ .order = 1, .space = .world },
            .ui => .{ .order = 2, .space = .screen },
        };
    }
};

const AllHookPayloads = engine.HookPayload(EcsBackend.Entity);

const GameHooks = struct {};

// Project Y-axis convention (engine#642) — single source of truth.
const project_y_axis: engine.core.YAxis = .up;
const Renderer = gfx.GfxRendererWith(BackendGfx, GameLayers, EcsBackend.Entity, project_y_axis);

const AssembledGame = engine.GameConfigWithYAxis(
    Renderer,
    EcsBackend,
    BackendInput,
    BackendAudio,
    GuiBackend,
    *GameHooks,
    LogSink,
    Components,
    DiscoveredGizmoCategories,
    project_y_axis,
);
const Prefabs = engine.PrefabRegistry(.{});

const Components = engine.ComponentRegistry(.{
    .VideoComponent = engine.core.VideoComponent,
});

const GizmoCatEntry = struct { name: []const u8, id: u8 };
const DiscoveredGizmoCategories: []const GizmoCatEntry = &.{};

const AllScripts = struct {
};

const Scripts = engine.ScriptRegistry(AllScripts);

const GameContext = struct {};
const Runner = engine.ScriptRunner(AllScripts, GameContext, EcsBackend);

const Views = engine.EmptyViewRegistry;

// Gizmo rendering is now handled by g.renderGizmos() — no generated code needed.
// The engine delegates to the renderer's renderGizmoDraws() method.
// acme_callback DESKTOP entry — a minimal CALLBACK-shaped `main.zig`
// (assembler#501 fixture). The acme windowing runtime owns the loop and invokes
// the exported init/frame/cleanup callbacks; the generated game splits init from
// the per-frame tick, so `runner` lives at module scope (declared through the
// module_vars hole) and the teardown runs in the exported `cleanup` callback
// (the cleanup_code hole). Restricted to the fixed, declared hole set — no sokol
// readback / imgui-bridge / bgfx-shell holes (those are backend-private and stay
// keyed to the built-in branches).
var g: AssembledGame = undefined;
    var hooks = GameHooks{};

var gpa = std.heap.DebugAllocator(.{}).init;
var runner: Runner = undefined;

const _PreviewTimespec = extern struct { sec: isize, nsec: isize };
const _preview_getenv = @extern(
    *const fn (name: [*:0]const u8) callconv(.c) ?[*:0]const u8,
    .{ .name = "getenv" },
);
const _preview_clock_gettime = @extern(
    *const fn (clk_id: c_int, tp: *_PreviewTimespec) callconv(.c) c_int,
    .{ .name = "clock_gettime" },
);
fn _preview_now_ms() u64 {
    const CLOCK_MONOTONIC: c_int = if (@import("builtin").os.tag == .macos) 6 else 1;
    var ts: _PreviewTimespec = undefined;
    _ = _preview_clock_gettime(CLOCK_MONOTONIC, &ts);
    return @intCast(@as(i64, ts.sec) * 1000 + @divTrunc(@as(i64, ts.nsec), 1_000_000));
}
fn _preview_input_mouse_pos(_: f32, _: f32) void {}
fn _preview_input_mouse_button(_: i32, _: bool) void {}

const screen_w: u32 = 800;
const screen_h: u32 = 600;
const screen_title = "LaBelle v2";
const target_fps: u32 = 60;

export fn init() callconv(.c) void {
    const allocator = gpa.allocator();
    g = AssembledGame.init(allocator);
    g.setHooks(&hooks);
    g.setScreenHeight(@as(f32, @floatFromInt(screen_h)));
    // ── Image asset backend wiring (Asset Streaming RFC, #53) ──
    // `engine.ImageLoader.setBackend` installs function-pointer adapters
    // that marshal between `BackendGfx`'s `DecodedImage`/`Texture` and
    // the engine's `DecodedImage` + flat `AssetTexture` (u32) handle.
    // A private slot table keyed by a fresh u32 preserves the full
    // backend `Texture` so unload releases every auxiliary GPU handle
    // (e.g. sokol's `sg.View` + `sg.Sampler`) — a plain `.id` passthrough
    // would leak those aux handles.
    const ImageBackendAdapter = struct {
        const MAX_IMAGE_ASSETS = 1024;
        const CATALOG_ID_BASE: u32 = 1 << 24;
        var slots: [MAX_IMAGE_ASSETS]?BackendGfx.Texture = [_]?BackendGfx.Texture{null} ** MAX_IMAGE_ASSETS;
        var renderer_ref: ?*Renderer = null;
        const supports_compressed = @hasDecl(BackendGfx, "isCompressed") and @hasDecl(BackendGfx, "compressedDims") and @hasDecl(BackendGfx, "uploadCompressed");
    
        fn decode(
            file_type: [:0]const u8,
            data: []const u8,
            alloc: std.mem.Allocator,
        ) anyerror!engine.DecodedImage {
            if (comptime supports_compressed) {
                if (BackendGfx.isCompressed(data)) {
                    const dims = BackendGfx.compressedDims(data) orelse return error.LoadFailed;
                    return .{ .pixels = try alloc.dupe(u8, data), .width = dims.width, .height = dims.height, .compressed = true };
                }
            }
            const d = try BackendGfx.decodeImage(file_type, data, alloc);
            return .{ .pixels = d.pixels, .width = d.width, .height = d.height };
        }
    
        fn upload(decoded: engine.DecodedImage) anyerror!engine.AssetTexture {
            var handle: u32 = MAX_IMAGE_ASSETS;
            for (slots, 0..) |slot, i| {
                if (slot == null) {
                    handle = @intCast(i);
                    break;
                }
            }
            if (handle == MAX_IMAGE_ASSETS) return error.ImageSlotsExhausted;
            const tex = blk: {
                if (comptime supports_compressed) {
                    if (decoded.compressed) break :blk try BackendGfx.uploadCompressed(decoded.pixels);
                }
                break :blk try BackendGfx.uploadTexture(.{
                    .pixels = decoded.pixels,
                    .width = decoded.width,
                    .height = decoded.height,
                });
            };
            slots[handle] = tex;
            const out_handle = handle + CATALOG_ID_BASE;
            if (renderer_ref) |r| r.registerCatalogTexture(out_handle, tex);
            return out_handle;
        }
    
        fn unload(texture: engine.AssetTexture) void {
            if (texture < CATALOG_ID_BASE) return;
            const idx = texture - CATALOG_ID_BASE;
            if (idx >= MAX_IMAGE_ASSETS) return;
            if (slots[idx]) |tex| {
                BackendGfx.unloadTexture(tex);
                slots[idx] = null;
            }
        }
    };
    engine.ImageLoader.setBackend(.{
        .decode = ImageBackendAdapter.decode,
        .upload = ImageBackendAdapter.upload,
        .unload = ImageBackendAdapter.unload,
    });
    ImageBackendAdapter.renderer_ref = g.renderer;

    runner = Runner.init(allocator, &g.active_world.ecs_backend);
    runner.setup(&g);
}

export fn frame() callconv(.c) void {
    const dt: f32 = 1.0 / @as(f32, @floatFromInt(@max(target_fps, 1)));
        const scaled_dt = dt * g.time_scale;
        if (scaled_dt > 0) {
            runner.tick(&g, scaled_dt);
        }
        g.dispatchEvents();
        if (comptime @TypeOf(runner).profiling_enabled) {
            g.script_profile_ptr = @ptrCast(@alignCast(&runner.profile));
            g.script_profile_count = @TypeOf(runner).script_count;
        }
    g.tick(dt);
    g.render();
}

export fn cleanup() callconv(.c) void {
    runner.deinit();
    g.deinit();
    _ = gpa.deinit();
}

pub fn main() void {
    window.run(.{
        .init_cb = &init,
        .frame_cb = &frame,
        .cleanup_cb = &cleanup,
        .w = screen_w,
        .h = screen_h,
        .title = screen_title,
    });
}
