/// Generated by labelle-cli — do not edit.
const std = @import("std");
const engine = @import("labelle-engine");
const BackendGfx = @import("backend_gfx");
const BackendInput = @import("backend_input");
const BackendAudio = @import("backend_audio");
const window = @import("backend_window");
// Log sink (default: stderr). Override in project template to disable or customize.
const LogSink = engine.core.StderrLogSink;
const EcsBackend = engine.MockEcsBackend(u32);
const GuiBackend = engine.StubGui;

// Zig 0.16 on iOS (labelle-assembler#774): the default Mach-O
// `std.debug.SelfInfo` calls `_dyld_get_image_header_containing_address`,
// which the iOS SDK does not export, so any panic/stack-trace path fails to
// LINK. `void` opts out of self-debug-info (traces print without symbols).
pub const debug = if (@import("builtin").target.os.tag == .ios) struct {
    pub const SelfInfo = void;
} else struct {};

// --- External backend contract verification (labelle-assembler#386 Phase 6b) ---
// Assert the fetched out-of-tree backend satisfies labelle-core's render /
// window / input contracts, naming any missing decl HERE rather than deep in
// engine wiring. Built-in backends skip this (vetted by the enum path).
comptime {
    const _backend_contract_core = @import("labelle-core");

    // --- Directional per-sub-surface contract-VERSION asserts (labelle-assembler#453) ---
    // Emitted BEFORE the shape asserts below: a `targets_<surface>_contract`
    // mismatch must report the DIRECTIONAL "upgrade labelle-core / upgrade the
    // backend" message FIRST -- if a shape assert @compileError'd first (a
    // decl the newer contract renamed/added), that directional guidance would
    // never fire. Each surface is checked only when the backend opts in by
    // declaring `targets_<surface>_contract` (@hasDecl guard = no flag day).
    const _bc_gfx = @import("backend_gfx");
    const _bc_window = @import("backend_window");
    const _bc_input = @import("backend_input");
    const _bc_audio = @import("backend_audio");
    if (@hasDecl(_bc_gfx, "targets_draw_contract")) {
        if (_bc_gfx.targets_draw_contract > _backend_contract_core.DRAW_CONTRACT_VERSION)
            @compileError(std.fmt.comptimePrint("backend targets draw-contract v{d} but this labelle-core provides v{d} -- upgrade labelle-core", .{ _bc_gfx.targets_draw_contract, _backend_contract_core.DRAW_CONTRACT_VERSION }));
        if (_bc_gfx.targets_draw_contract < _backend_contract_core.DRAW_CONTRACT_VERSION)
            @compileError(std.fmt.comptimePrint("backend targets draw-contract v{d} but this labelle-core expects v{d} -- a breaking draw-contract change landed; upgrade the backend", .{ _bc_gfx.targets_draw_contract, _backend_contract_core.DRAW_CONTRACT_VERSION }));
    }
    if (@hasDecl(_bc_gfx, "targets_loader_contract")) {
        if (_bc_gfx.targets_loader_contract > _backend_contract_core.LOADER_CONTRACT_VERSION)
            @compileError(std.fmt.comptimePrint("backend targets loader-contract v{d} but this labelle-core provides v{d} -- upgrade labelle-core", .{ _bc_gfx.targets_loader_contract, _backend_contract_core.LOADER_CONTRACT_VERSION }));
        if (_bc_gfx.targets_loader_contract < _backend_contract_core.LOADER_CONTRACT_VERSION)
            @compileError(std.fmt.comptimePrint("backend targets loader-contract v{d} but this labelle-core expects v{d} -- a breaking loader-contract change landed; upgrade the backend", .{ _bc_gfx.targets_loader_contract, _backend_contract_core.LOADER_CONTRACT_VERSION }));
    }
    if (@hasDecl(_bc_window, "targets_window_contract")) {
        if (_bc_window.targets_window_contract > _backend_contract_core.WINDOW_CONTRACT_VERSION)
            @compileError(std.fmt.comptimePrint("backend targets window-contract v{d} but this labelle-core provides v{d} -- upgrade labelle-core", .{ _bc_window.targets_window_contract, _backend_contract_core.WINDOW_CONTRACT_VERSION }));
        if (_bc_window.targets_window_contract < _backend_contract_core.WINDOW_CONTRACT_VERSION)
            @compileError(std.fmt.comptimePrint("backend targets window-contract v{d} but this labelle-core expects v{d} -- a breaking window-contract change landed; upgrade the backend", .{ _bc_window.targets_window_contract, _backend_contract_core.WINDOW_CONTRACT_VERSION }));
    }
    if (@hasDecl(_bc_input, "targets_input_contract")) {
        if (_bc_input.targets_input_contract > _backend_contract_core.INPUT_CONTRACT_VERSION)
            @compileError(std.fmt.comptimePrint("backend targets input-contract v{d} but this labelle-core provides v{d} -- upgrade labelle-core", .{ _bc_input.targets_input_contract, _backend_contract_core.INPUT_CONTRACT_VERSION }));
        if (_bc_input.targets_input_contract < _backend_contract_core.INPUT_CONTRACT_VERSION)
            @compileError(std.fmt.comptimePrint("backend targets input-contract v{d} but this labelle-core expects v{d} -- a breaking input-contract change landed; upgrade the backend", .{ _bc_input.targets_input_contract, _backend_contract_core.INPUT_CONTRACT_VERSION }));
    }
    if (@hasDecl(_bc_audio, "targets_audio_playback_contract")) {
        if (_bc_audio.targets_audio_playback_contract > _backend_contract_core.AUDIO_PLAYBACK_CONTRACT_VERSION)
            @compileError(std.fmt.comptimePrint("backend targets audio-playback-contract v{d} but this labelle-core provides v{d} -- upgrade labelle-core", .{ _bc_audio.targets_audio_playback_contract, _backend_contract_core.AUDIO_PLAYBACK_CONTRACT_VERSION }));
        if (_bc_audio.targets_audio_playback_contract < _backend_contract_core.AUDIO_PLAYBACK_CONTRACT_VERSION)
            @compileError(std.fmt.comptimePrint("backend targets audio-playback-contract v{d} but this labelle-core expects v{d} -- a breaking audio-playback-contract change landed; upgrade the backend", .{ _bc_audio.targets_audio_playback_contract, _backend_contract_core.AUDIO_PLAYBACK_CONTRACT_VERSION }));
    }
    if (@hasDecl(_bc_audio, "targets_audio_loader_contract")) {
        if (_bc_audio.targets_audio_loader_contract > _backend_contract_core.AUDIO_LOADER_CONTRACT_VERSION)
            @compileError(std.fmt.comptimePrint("backend targets audio-loader-contract v{d} but this labelle-core provides v{d} -- upgrade labelle-core", .{ _bc_audio.targets_audio_loader_contract, _backend_contract_core.AUDIO_LOADER_CONTRACT_VERSION }));
        if (_bc_audio.targets_audio_loader_contract < _backend_contract_core.AUDIO_LOADER_CONTRACT_VERSION)
            @compileError(std.fmt.comptimePrint("backend targets audio-loader-contract v{d} but this labelle-core expects v{d} -- a breaking audio-loader-contract change landed; upgrade the backend", .{ _bc_audio.targets_audio_loader_contract, _backend_contract_core.AUDIO_LOADER_CONTRACT_VERSION }));
    }

    // Shape asserts run AFTER the version asserts above (see note there):
    // the backend must satisfy labelle-core's render / window / input contract
    // SURFACE (every required decl present) once its version is known-compatible.
    _backend_contract_core.assertBackend(@import("backend_gfx"));
    _backend_contract_core.assertWindow(@import("backend_window"));
    _backend_contract_core.assertInput(@import("backend_input"));
}

const gfx = @import("labelle-gfx");

const GameLayers = enum(u8) {
    background,
    world,
    ui,

    pub fn config(self: GameLayers) gfx.LayerConfig {
        return switch (self) {
            .background => .{ .order = 0, .space = .screen },
            .world => .{ .order = 1, .space = .world },
            .ui => .{ .order = 2, .space = .screen },
        };
    }
};

const AllHookPayloads = engine.HookPayload(EcsBackend.Entity);

const GameHooks = struct {};

// Project Y-axis convention (engine#642) — single source of truth.
const project_y_axis: engine.core.YAxis = .up;
const Renderer = gfx.GfxRendererWith(BackendGfx, GameLayers, EcsBackend.Entity, project_y_axis);

const AssembledGame = engine.GameConfigWithYAxis(
    Renderer,
    EcsBackend,
    BackendInput,
    BackendAudio,
    GuiBackend,
    *GameHooks,
    LogSink,
    Components,
    DiscoveredGizmoCategories,
    project_y_axis,
);
const Prefabs = engine.PrefabRegistry(.{});

const Components = engine.ComponentRegistry(.{
    .VideoComponent = engine.core.VideoComponent,
});

const GizmoCatEntry = struct { name: []const u8, id: u8 };
const DiscoveredGizmoCategories: []const GizmoCatEntry = &.{};

const AllScripts = struct {
};

const Scripts = engine.ScriptRegistry(AllScripts);

const GameContext = struct {};
const Runner = engine.ScriptRunner(AllScripts, GameContext, EcsBackend);

const Views = engine.EmptyViewRegistry;

// Gizmo rendering is now handled by g.renderGizmos() — no generated code needed.
// The engine delegates to the renderer's renderGizmoDraws() method.
var runner: Runner = undefined;

const _PreviewTimespec = extern struct { sec: isize, nsec: isize };
const _preview_getenv = @extern(
    *const fn (name: [*:0]const u8) callconv(.c) ?[*:0]const u8,
    .{ .name = "getenv" },
);
const _preview_clock_gettime = @extern(
    *const fn (clk_id: c_int, tp: *_PreviewTimespec) callconv(.c) c_int,
    .{ .name = "clock_gettime" },
);
fn _preview_now_ms() u64 {
    const CLOCK_MONOTONIC: c_int = if (@import("builtin").os.tag == .macos) 6 else 1;
    var ts: _PreviewTimespec = undefined;
    _ = _preview_clock_gettime(CLOCK_MONOTONIC, &ts);
    return @intCast(@as(i64, ts.sec) * 1000 + @divTrunc(@as(i64, ts.nsec), 1_000_000));
}

// ── Sokol PBO readback gating (labelle-assembler#122 slice 1) ──
// Default sokol-zig picks GLCORE on Linux desktop, GLES3 on Android
// and emscripten, Metal on Darwin, D3D11 on Windows. The GL PBO
// path only applies to the first two; Metal / D3D11 are separate
// slices (IOSurface, staging). Comptime-gating on builtin.os.tag
// keeps the GL externs out of non-GL link lines so e.g. a sokol
// macOS build (Metal) doesn't fail to resolve `glReadPixels`.
// Android in Zig is `os.tag == .linux` with `abi == .android` /
// `.androideabi`, so the simple `.linux` arm already covers both
// desktop GLCORE and Android GLES3. Emscripten / wasm32 is left
// as a no-op for now — WebGL2 has limited PBO support and slice 1
// doesn't ship a wasm story (see PR body / #122 follow-ups).
const _sokol_preview_gl_enabled: bool = switch (@import("builtin").os.tag) {
    .linux => true,
    else => false,
};

// PBO state at module scope — sokol's init / frame / cleanup
// callbacks are separate functions, so the locals raylib's main()
// uses for the same purpose need to live at file scope here.
// `_preview_allocator` mirrors the allocator the game uses; it's
// stashed in the init callback so frame + cleanup can reach the
// CPU staging buffer without re-deriving it from `g`.
var _preview_allocator: std.mem.Allocator = std.mem.Allocator{ .ptr = undefined, .vtable = undefined };
var _preview_pbos: [3]c_uint = .{ 0, 0, 0 };
var _preview_pbo_bytes: usize = 0;
var _preview_pbo_initialized: bool = false;
var _preview_frame_idx: u64 = 0;
var _preview_last_w: u32 = 0;
var _preview_last_h: u32 = 0;
var _preview_pixel_buf: []u8 = &[_]u8{};

// GL extern decls live inside a struct-namespace gated on
// `_sokol_preview_gl_enabled`. The `else struct {}` branch holds
// no symbols, so a Metal / D3D11 sokol build never emits an
// undefined-symbol reference to `glReadPixels` etc.
const _SokolPreviewGl = if (_sokol_preview_gl_enabled) struct {
    pub const PIXEL_PACK_BUFFER: c_uint = 0x88EB;
    pub const STREAM_READ: c_uint = 0x88E1;
    // GL_MAP_READ_BIT — bit-flag for glMapBufferRange's access.
    // Core in GL 3.0+ AND GLES 3.0+; glMapBuffer is desktop-only
    // and ships on GLES only as `GL_OES_mapbuffer`, so the range
    // variant is the portable choice for Android GLES3 builds.
    pub const MAP_READ_BIT: c_uint = 0x0001;
    pub const PACK_ALIGNMENT: c_uint = 0x0D05;
    pub const RGBA: c_uint = 0x1908;
    pub const UNSIGNED_BYTE: c_uint = 0x1401;
    pub const pixelStorei = @extern(
        *const fn (pname: c_uint, param: c_int) callconv(.c) void,
        .{ .name = "glPixelStorei" },
    );
    pub const genBuffers = @extern(
        *const fn (n: c_int, buffers: [*]c_uint) callconv(.c) void,
        .{ .name = "glGenBuffers" },
    );
    pub const deleteBuffers = @extern(
        *const fn (n: c_int, buffers: [*]const c_uint) callconv(.c) void,
        .{ .name = "glDeleteBuffers" },
    );
    pub const bindBuffer = @extern(
        *const fn (target: c_uint, buffer: c_uint) callconv(.c) void,
        .{ .name = "glBindBuffer" },
    );
    pub const bufferData = @extern(
        *const fn (target: c_uint, size: isize, data: ?*const anyopaque, usage: c_uint) callconv(.c) void,
        .{ .name = "glBufferData" },
    );
    pub const readPixels = @extern(
        *const fn (x: c_int, y: c_int, w: c_int, h: c_int, fmt: c_uint, ty: c_uint, data: ?*anyopaque) callconv(.c) void,
        .{ .name = "glReadPixels" },
    );
    pub const mapBufferRange = @extern(
        *const fn (target: c_uint, offset: isize, length: isize, access: c_uint) callconv(.c) ?*anyopaque,
        .{ .name = "glMapBufferRange" },
    );
    pub const unmapBuffer = @extern(
        *const fn (target: c_uint) callconv(.c) u8,
        .{ .name = "glUnmapBuffer" },
    );
} else struct {};

// ── Sokol D3D11 readback gating (labelle-assembler#126) ──
// Default sokol-zig picks D3D11 on Windows desktop. The staging-
// texture readback path only applies there; on Linux/Android sokol
// runs GLCORE/GLES3 (the block above), and on Darwin sokol runs
// Metal (slice 3, #125). The `comptime`-gated externs and the
// `struct {}` else branch keep the D3D11 entry points off the
// link line for non-Windows targets.
const _sokol_preview_d3d11_enabled: bool = @import("builtin").os.tag == .windows;

// Staging-texture ring + book-keeping at module scope (same
// rationale as the GL block — sokol's `init` / `frame` / `cleanup`
// callbacks have no shared local stack frame).
//
// `_preview_d3d11_staging` holds 3 `ID3D11Texture2D*` (opaque)
// allocated on the first frame / on resize; the publish loop
// `CopyResource`s the back-buffer into slot `N % 3` and `Map`s
// slot `(N-2) % 3` — same 3-deep ring + 2-frame priming gap as
// the GL PBO path keeps DMA / GPU stalls out of the frame loop.
var _preview_d3d11_staging: [3]?*anyopaque = .{ null, null, null };
var _preview_d3d11_initialized: bool = false;

// COM dispatch helpers. D3D11 / DXGI interfaces are layouts where
// the first field is a pointer to a function-pointer vtable. We
// only need a handful of methods, all at well-known stable
// indices (see helpers doc-comment above). The IID below is
// `IID_ID3D11Texture2D` — `{6F15AAF2-D208-4E89-9AB4-489535D34F9C}`
// in little-endian DWORD/WORD byte order.
const _SokolPreviewD3d11 = if (_sokol_preview_d3d11_enabled) struct {
    // D3D11_USAGE_STAGING = 3; CPU_ACCESS_READ = 0x20000.
    // D3D11_MAP_READ = 1; DXGI_FORMAT_B8G8R8A8_UNORM = 87.
    pub const USAGE_STAGING: c_uint = 3;
    pub const CPU_ACCESS_READ: c_uint = 0x20000;
    pub const MAP_READ: c_uint = 1;
    pub const FORMAT_B8G8R8A8_UNORM: c_uint = 87;

    // `_Guid` mirrors Windows `GUID` / `IID` — 16 bytes, mixed
    // endianness in the binary form. Hand-coded byte sequence
    // avoids dragging in Win32 headers from the generated code.
    pub const _Guid = extern struct {
        data1: u32,
        data2: u16,
        data3: u16,
        data4: [8]u8,
    };
    pub const IID_ID3D11Texture2D: _Guid = .{
        .data1 = 0x6F15AAF2,
        .data2 = 0xD208,
        .data3 = 0x4E89,
        .data4 = .{ 0x9A, 0xB4, 0x48, 0x95, 0x35, 0xD3, 0x4F, 0x9C },
    };

    // Mapped subresource layout — matches D3D11_MAPPED_SUBRESOURCE.
    pub const MappedSubresource = extern struct {
        data: ?*anyopaque,
        row_pitch: u32,
        depth_pitch: u32,
    };

    // D3D11_TEXTURE2D_DESC. SampleDesc is `{count, quality}`.
    pub const Texture2DDesc = extern struct {
        width: u32,
        height: u32,
        mip_levels: u32,
        array_size: u32,
        format: c_uint,
        sample_count: u32,
        sample_quality: u32,
        usage: c_uint,
        bind_flags: c_uint,
        cpu_access_flags: c_uint,
        misc_flags: c_uint,
    };

    // Sokol C-symbol entry points — `sg_d3d11_device()`,
    // `sg_d3d11_device_context()`, `sapp_d3d11_get_swap_chain()`
    // are part of the public sokol-gfx / sokol-app API and link
    // into any sokol-on-Windows build via the sokol-zig dep.
    pub const sgDevice = @extern(
        *const fn () callconv(.c) ?*anyopaque,
        .{ .name = "sg_d3d11_device" },
    );
    pub const sgDeviceContext = @extern(
        *const fn () callconv(.c) ?*anyopaque,
        .{ .name = "sg_d3d11_device_context" },
    );
    pub const sappSwapChain = @extern(
        *const fn () callconv(.c) ?*anyopaque,
        .{ .name = "sapp_d3d11_get_swap_chain" },
    );

    // `Object` is a placeholder for any COM interface pointer; the
    // first field is always a pointer to the vtable, which is
    // itself a `[*]const *const fn () callconv(.c) i32`. We dispatch
    // by indexing into that table at the documented method index.
    pub const Object = extern struct { vtbl: [*]const *const anyopaque };

    /// IDXGISwapChain::GetBuffer — vtable index 9.
    /// Signature: HRESULT GetBuffer(UINT Buffer, REFIID riid, void** ppSurface).
    pub fn swapChainGetBuffer(sc: *anyopaque, buffer: u32, riid: *const _Guid, out: *?*anyopaque) i32 {
        const obj: *Object = @ptrCast(@alignCast(sc));
        const fp: *const fn (*anyopaque, u32, *const _Guid, *?*anyopaque) callconv(.c) i32 = @ptrCast(obj.vtbl[9]);
        return fp(sc, buffer, riid, out);
    }

    /// ID3D11Device::CreateTexture2D — vtable index 5.
    /// Signature: HRESULT CreateTexture2D(const D3D11_TEXTURE2D_DESC*, const D3D11_SUBRESOURCE_DATA*, ID3D11Texture2D**).
    pub fn deviceCreateTexture2D(dev: *anyopaque, desc: *const Texture2DDesc, out: *?*anyopaque) i32 {
        const obj: *Object = @ptrCast(@alignCast(dev));
        const fp: *const fn (*anyopaque, *const Texture2DDesc, ?*const anyopaque, *?*anyopaque) callconv(.c) i32 = @ptrCast(obj.vtbl[5]);
        return fp(dev, desc, null, out);
    }

    /// ID3D11DeviceContext::Map — vtable index 14.
    /// Signature: HRESULT Map(ID3D11Resource*, UINT subresource, D3D11_MAP, UINT flags, D3D11_MAPPED_SUBRESOURCE*).
    pub fn contextMap(ctx: *anyopaque, resource: *anyopaque, subresource: u32, map_type: c_uint, flags: u32, out: *MappedSubresource) i32 {
        const obj: *Object = @ptrCast(@alignCast(ctx));
        const fp: *const fn (*anyopaque, *anyopaque, u32, c_uint, u32, *MappedSubresource) callconv(.c) i32 = @ptrCast(obj.vtbl[14]);
        return fp(ctx, resource, subresource, map_type, flags, out);
    }

    /// ID3D11DeviceContext::Unmap — vtable index 15.
    /// Signature: void Unmap(ID3D11Resource*, UINT subresource).
    pub fn contextUnmap(ctx: *anyopaque, resource: *anyopaque, subresource: u32) void {
        const obj: *Object = @ptrCast(@alignCast(ctx));
        const fp: *const fn (*anyopaque, *anyopaque, u32) callconv(.c) void = @ptrCast(obj.vtbl[15]);
        fp(ctx, resource, subresource);
    }

    /// ID3D11DeviceContext::CopyResource — vtable index 47.
    /// Signature: void CopyResource(ID3D11Resource* dst, ID3D11Resource* src).
    pub fn contextCopyResource(ctx: *anyopaque, dst: *anyopaque, src: *anyopaque) void {
        const obj: *Object = @ptrCast(@alignCast(ctx));
        const fp: *const fn (*anyopaque, *anyopaque, *anyopaque) callconv(.c) void = @ptrCast(obj.vtbl[47]);
        fp(ctx, dst, src);
    }

    /// IUnknown::Release — vtable index 2. Used to release the
    /// AddRef'd back-buffer pointer from `GetBuffer` and to drop
    /// the staging textures on cleanup / resize.
    pub fn release(obj_ptr: *anyopaque) u32 {
        const obj: *Object = @ptrCast(@alignCast(obj_ptr));
        const fp: *const fn (*anyopaque) callconv(.c) u32 = @ptrCast(obj.vtbl[2]);
        return fp(obj_ptr);
    }
} else struct {};

// ── Sokol Metal/IOSurface preview seam (labelle-assembler#140) ─
// All Path-A state + ring management + cleanup now lives in the
// backend module (`backends/sokol/src/window.zig:preview_mtl`).
// The codegen owns only:
//   1. The comptime enable gate (aliased from the backend).
//   2. Five tiny bridge fns that wrap `engine.Preview` methods
//      behind an `*anyopaque` boundary so the backend never needs
//      an engine type-import (the engine module would otherwise
//      have to be wired through the backend's build graph too).
//   3. The vtable-attach call inside the init callback (see
//      PREVIEW_INIT_CALLBACK below).
const _sokol_preview_metal_enabled = window.preview_metal_enabled;

// Bridge fns — pure wrappers over the engine.Preview methods the
// backend's preview_mtl namespace drives via its vtable. These
// live in module scope because the vtable is wired up once during
// init and persists for the program's lifetime.
fn _preview_mtl_begin_stream_bridge(ctx: *anyopaque, w: u32, h: u32) anyerror!void {
    const p: *engine.Preview = @ptrCast(@alignCast(ctx));
    return p.beginFrameStreamIOSurface(w, h);
}
fn _preview_mtl_get_surface_bridge(ctx: *anyopaque, slot: u32) ?*anyopaque {
    const p: *engine.Preview = @ptrCast(@alignCast(ctx));
    // getIOSurfaceAt returns `??*opaque` — outer optional means
    // "slot in range", inner means "IOSurfaceRef itself nullable".
    const maybe_ref = p.getIOSurfaceAt(slot) orelse return null;
    const ref = maybe_ref orelse return null;
    return @ptrCast(ref);
}
fn _preview_mtl_signal_bridge(ctx: *anyopaque, slot: u32) anyerror!void {
    const p: *engine.Preview = @ptrCast(@alignCast(ctx));
    return p.signalSlotReady(slot);
}
fn _preview_mtl_end_stream_bridge(ctx: *anyopaque) void {
    const p: *engine.Preview = @ptrCast(@alignCast(ctx));
    p.endFrameStreamIOSurface();
}
fn _preview_mtl_accepted_bridge(ctx: *anyopaque) bool {
    const p: *const engine.Preview = @ptrCast(@alignCast(ctx));
    return p.isFrameAccepted();
}
fn _preview_input_mouse_pos(_: f32, _: f32) void {}
fn _preview_input_mouse_button(_: i32, _: bool) void {}
var g: AssembledGame = undefined;
    var hooks = GameHooks{};

var gpa = std.heap.DebugAllocator(.{}).init;
const screen_w: u32 = 800;
const screen_h: u32 = 600;
const screen_title = "LaBelle v2";
const target_fps: u32 = 60;
export fn init() callconv(.c) void {
    const allocator = gpa.allocator();
    g = AssembledGame.init(allocator);
    g.setHooks(&hooks);
    // ── Image asset backend wiring (Asset Streaming RFC, #53) ──
    // `engine.ImageLoader.setBackend` installs function-pointer adapters
    // that marshal between `BackendGfx`'s `DecodedImage`/`Texture` and
    // the engine's `DecodedImage` + flat `AssetTexture` (u32) handle.
    // A private slot table keyed by a fresh u32 preserves the full
    // backend `Texture` so unload releases every auxiliary GPU handle
    // (e.g. sokol's `sg.View` + `sg.Sampler`) — a plain `.id` passthrough
    // would leak those aux handles.
    const ImageBackendAdapter = struct {
        const MAX_IMAGE_ASSETS = 1024;
        const CATALOG_ID_BASE: u32 = 1 << 24;
        var slots: [MAX_IMAGE_ASSETS]?BackendGfx.Texture = [_]?BackendGfx.Texture{null} ** MAX_IMAGE_ASSETS;
        var renderer_ref: ?*Renderer = null;
        const supports_compressed = @hasDecl(BackendGfx, "isCompressed") and @hasDecl(BackendGfx, "compressedDims") and @hasDecl(BackendGfx, "uploadCompressed");
    
        fn decode(
            file_type: [:0]const u8,
            data: []const u8,
            alloc: std.mem.Allocator,
        ) anyerror!engine.DecodedImage {
            if (comptime supports_compressed) {
                if (BackendGfx.isCompressed(data)) {
                    const dims = BackendGfx.compressedDims(data) orelse return error.LoadFailed;
                    return .{ .pixels = try alloc.dupe(u8, data), .width = dims.width, .height = dims.height, .compressed = true };
                }
            }
            const d = try BackendGfx.decodeImage(file_type, data, alloc);
            return .{ .pixels = d.pixels, .width = d.width, .height = d.height };
        }
    
        fn upload(decoded: engine.DecodedImage) anyerror!engine.AssetTexture {
            var handle: u32 = MAX_IMAGE_ASSETS;
            for (slots, 0..) |slot, i| {
                if (slot == null) {
                    handle = @intCast(i);
                    break;
                }
            }
            if (handle == MAX_IMAGE_ASSETS) return error.ImageSlotsExhausted;
            const tex = blk: {
                if (comptime supports_compressed) {
                    if (decoded.compressed) break :blk try BackendGfx.uploadCompressed(decoded.pixels);
                }
                break :blk try BackendGfx.uploadTexture(.{
                    .pixels = decoded.pixels,
                    .width = decoded.width,
                    .height = decoded.height,
                });
            };
            slots[handle] = tex;
            const out_handle = handle + CATALOG_ID_BASE;
            if (renderer_ref) |r| r.registerCatalogTexture(out_handle, tex);
            return out_handle;
        }
    
        fn unload(texture: engine.AssetTexture) void {
            if (texture < CATALOG_ID_BASE) return;
            const idx = texture - CATALOG_ID_BASE;
            if (idx >= MAX_IMAGE_ASSETS) return;
            if (slots[idx]) |tex| {
                routed: {
                    if (comptime @hasDecl(Renderer, "unloadTexture")) {
                        if (renderer_ref) |r| {
                            const Param = @typeInfo(@TypeOf(Renderer.unloadTexture)).@"fn".params[1].type.?;
                            const typed: Param = if (comptime @typeInfo(Param) == .@"enum") @enumFromInt(texture) else @intCast(texture);
                            r.unloadTexture(typed);
                            break :routed;
                        }
                    }
                    BackendGfx.unloadTexture(tex);
                }
                slots[idx] = null;
            }
        }
    };
    engine.ImageLoader.setBackend(.{
        .decode = ImageBackendAdapter.decode,
        .upload = ImageBackendAdapter.upload,
        .unload = ImageBackendAdapter.unload,
    });
    ImageBackendAdapter.renderer_ref = g.renderer;

    runner = Runner.init(allocator, &g.active_world.ecs_backend);
    runner.setup(&g);
    @import("backend_input").initAndroidGamepad();
}
export fn frame() callconv(.c) void {
    const dt: f32 = 0.016;
        const scaled_dt = dt * g.time_scale;
        if (scaled_dt > 0) {
            runner.tick(&g, scaled_dt);
        }
        g.dispatchEvents();
        if (comptime @TypeOf(runner).profiling_enabled) {
            g.script_profile_ptr = @ptrCast(@alignCast(&runner.profile));
            g.script_profile_count = @TypeOf(runner).script_count;
        }
    g.tick(dt);
    g.render();
}
export fn cleanup() callconv(.c) void {
    runner.deinit();
    g.deinit();
}
export fn sokol_main(argc: c_int, argv: [*][*:0]u8) window.Desc {
    _ = argc;
    _ = argv;
    return window.makeDesc(.{ .init_cb = &init });
}
